// AUTO-GENERATED FROM POSTGRES — DO NOT EDIT BY HAND.
// Source of truth: the `products` table in the self-hosted Postgres.
// Regenerate:  node scripts/catalog/04-generate-catalog.mjs
// Generated:   2026-08-04T08:15:15.237Z  (95 products)

export interface Product {
  slug: string; name: string; variant: string; price: number;
  category: string;
  stock: number; description: string;
  // The details object maps to a jsonb column, so its shape is open by design.
  // Named keys are the ones the UI reads; the index signature stops every new
  // attribute (fits, condition, returns and so on) from being a type error.
  details: {
    dimensions?: string; material?: string; care?: string; weight?: string; packWeight?: string;
    age?: string; made?: string; personalisation?: string; images?: string[];
    [key: string]: string | string[] | undefined;
  };
  imagePlaceholder: { bg: string; initials: string; };
  imageUrl: string; cjPid?: string; cjPrice?: string;
  hidden?: boolean;
}

export const products: Product[] = [
  { slug: "mdf-circle-cutout", name: "MDF Circle Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Perfectly round circle cutout made from 3mm MDF with smooth laser-cut edges. A versatile craft essential for coasters, ornaments, monogram bases, and mixed media art. Takes acrylic paint and wood stain exceptionally well. Approximate size: 10cm diameter.",
    details: { images: ["/images/mdf/mdf-circle-cutout.png"], weight: "35g", material: "3mm MDF", dimensions: "10cm diameter" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MC" },
    imageUrl: "/images/mdf/mdf-circle-cutout.png" },
  { slug: "mdf-crescent-moon-cutout", name: "MDF Crescent Moon Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Whimsical crescent moon shape laser-cut from 3mm MDF. Perfect for nursery mobiles, celestial-themed decor, and dreamy craft projects. Smooth finish ready for glitter, paint, or resin coating. Approximate size: 9cm x 7cm.",
    details: { images: ["/images/mdf/mdf-crescent-moon-cutout.png"], weight: "25g", material: "3mm MDF", dimensions: "9cm x 7cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MC" },
    imageUrl: "/images/mdf/mdf-crescent-moon-cutout.png" },
  { slug: "mdf-cross-cutout", name: "MDF Cross Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Simple cross shape cut from 3mm MDF with laser precision. Ideal for religious crafts, memorial art, church decorations, and personalized gifts. Smooth surface takes paint and embellishments beautifully. Approximate size: 10cm x 10cm.",
    details: { images: ["/images/mdf/mdf-cross-cutout.png"], weight: "30g", material: "3mm MDF", dimensions: "10cm x 10cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MC" },
    imageUrl: "/images/mdf/mdf-cross-cutout.png" },
  { slug: "mdf-diamond-cutout", name: "MDF Diamond Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Geometric diamond shape laser-cut from 3mm MDF. This modern cutout is perfect for geometric wall art, jewelry making, and contemporary craft projects. Clean lines and smooth edges straight from the laser. Approximate size: 7cm x 10cm.",
    details: { images: ["/images/mdf/mdf-diamond-cutout.png"], weight: "28g", material: "3mm MDF", dimensions: "7cm x 10cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MD" },
    imageUrl: "/images/mdf/mdf-diamond-cutout.png" },
  { slug: "mdf-elephant-cutout", name: "MDF Elephant Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Charming 2D flat elephant cutout silhouette precision-cut from premium 3mm MDF, offered in two finishes: Raw MDF (ready for paint, markers, and DIY craft kits) and White Finish (Bright White Coloring Canvas, perfect for standard crayons and markers). This design is highly optimized and easy to cut on any CO2 laser machine and is ideal for nursery decor, children's educational play, DIY craft projects, wedding themes, and personalized gifts. The clean laser-cut edges ensure a smooth, professional finish. Available in two sizes: 4.8cm x 4.8cm and 9.6cm x 9.6cm, 3mm thickness.",
    details: { images: ["/images/mdf/mdf-elephant-cutout-hero.png"], weight: "40g", material: "Premium MDF / Pre-bonded Matte Paper Layer", dimensions: "4.8cm x 4.8cm or 9.6cm x 9.6cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "ME" },
    imageUrl: "/images/mdf/mdf-elephant-cutout-hero.png" },
  { slug: "mdf-heart-cutout", name: "MDF Heart Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Beautiful laser-cut heart shape crafted from 3mm MDF. Perfect for DIY craft projects, scrapbooking, wedding decorations, or personalized gifts. Smooth edges and lightweight design make this cutout easy to paint, stain, or decorate. Approximate size: 8cm x 8cm.",
    details: { images: ["/images/mdf/mdf-heart-cutout.png"], weight: "30g", material: "3mm MDF", dimensions: "8cm x 8cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MH" },
    imageUrl: "/images/mdf/mdf-heart-cutout.png" },
  { slug: "mdf-hexagon-cutout", name: "MDF Hexagon Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Trendy hexagonal cutout laser-cut from 3mm MDF. Create stunning geometric wall displays or use as a base for resin art, coasters, and decorative tiles. Precision edges ensure perfect tessellation. Approximate size: 8cm per side.",
    details: { images: ["/images/mdf/mdf-hexagon-cutout.png"], weight: "30g", material: "3mm MDF", dimensions: "8cm per side" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MH" },
    imageUrl: "/images/mdf/mdf-hexagon-cutout.png" },
  { slug: "mdf-oval-cutout", name: "MDF Oval Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Classic oval shape cut from 3mm MDF with smooth laser-cut edges. A versatile blank for frame-making, portrait bases, monogram projects, and vintage-style decor. The smooth surface is ready for any finish. Approximate size: 12cm x 8cm.",
    details: { images: ["/images/mdf/mdf-oval-cutout.png"], weight: "35g", material: "3mm MDF", dimensions: "12cm x 8cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MO" },
    imageUrl: "/images/mdf/mdf-oval-cutout.png" },
  { slug: "mdf-square-cutout", name: "MDF Square Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Perfect square cutout precision-cut from 3mm MDF. An essential craft blank for coasters, picture frame bases, tile mosaics, and pixel art. Laser-cut for exact dimensions and smooth edges. Approximate size: 10cm x 10cm.",
    details: { images: ["/images/mdf/mdf-square-cutout.png"], weight: "35g", material: "3mm MDF", dimensions: "10cm x 10cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MS" },
    imageUrl: "/images/mdf/mdf-square-cutout.png" },
  { slug: "mdf-star-cutout", name: "MDF Star Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Five-pointed star cutout precision-cut from 3mm MDF using advanced laser technology. Ideal for wall art, party decorations, and children's craft activities. The smooth sanded surface accepts paint, glitter, and markers beautifully. Approximate size: 7cm x 7cm.",
    details: { images: ["/images/mdf/mdf-star-cutout.png"], weight: "25g", material: "3mm MDF", dimensions: "7cm x 7cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MS" },
    imageUrl: "/images/mdf/mdf-star-cutout.png" },
  { slug: "mdf-triangle-cutout", name: "MDF Triangle Cutout – 3mm Laser Cut", variant: "Good Value", price: 1, category: "MDF Cutouts", stock: 100,
    description: "Equilateral triangle cutout precision-cut from 3mm MDF. Great for geometric art, bunting, mobile making, and educational math projects. Clean laser-cut lines for professional results. Approximate size: 8cm per side.",
    details: { images: ["/images/mdf/mdf-triangle-cutout.png"], weight: "25g", material: "3mm MDF", dimensions: "8cm per side" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MT" },
    imageUrl: "/images/mdf/mdf-triangle-cutout.png" },
  { slug: "mdf-bird-cutout", name: "MDF Bird Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Graceful bird in flight silhouette crafted from 3mm MDF with laser cutting. This elegant cutout is perfect for spring decor, nature-themed crafts, and wall art groupings. Lightweight and easy to paint. Approximate size: 10cm x 6cm.",
    details: { images: ["/images/mdf/mdf-bird-cutout.png"], weight: "22g", material: "3mm MDF", dimensions: "10cm x 6cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MB" },
    imageUrl: "/images/mdf/mdf-bird-cutout.png" },
  { slug: "mdf-bunny-cutout", name: "MDF Bunny Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Sweet bunny rabbit silhouette precision-cut from 3mm MDF. Ideal for Easter decorations, children's room decor, and handmade greeting cards. Laser-cut for consistent quality and smooth finish. Approximate size: 8cm x 12cm.",
    details: { images: ["/images/mdf/mdf-bunny-cutout.png"], weight: "32g", material: "3mm MDF", dimensions: "8cm x 12cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MB" },
    imageUrl: "/images/mdf/mdf-bunny-cutout.png" },
  { slug: "mdf-butterfly-cutout", name: "MDF Butterfly Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Elegant butterfly silhouette laser-cut from premium 3mm MDF. This delicate cutout features intricate wing detail perfect for scrapbooking, card making, and home decor projects. Easy to paint and customize. Approximate size: 10cm x 8cm.",
    details: { images: ["/images/mdf/mdf-butterfly-cutout.png"], weight: "35g", material: "3mm MDF", dimensions: "10cm x 8cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MB" },
    imageUrl: "/images/mdf/mdf-butterfly-cutout.png" },
  { slug: "mdf-cat-cutout", name: "MDF Cat Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Adorable cat silhouette cutout crafted from 3mm MDF with precision laser cutting. Perfect for pet lovers, nursery wall art, and creative craft projects. Smooth surface ready for painting or decoupage. Approximate size: 9cm x 11cm.",
    details: { images: ["/images/mdf/mdf-cat-cutout.png"], weight: "35g", material: "3mm MDF", dimensions: "9cm x 11cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MC" },
    imageUrl: "/images/mdf/mdf-cat-cutout.png" },
  { slug: "mdf-dog-cutout", name: "MDF Dog Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Friendly dog silhouette cut from 3mm MDF using precision laser technology. Perfect for pet-themed crafts, keychain blanks, and decorative projects. Paint, stain, or embellish this smooth MDF cutout. Approximate size: 10cm x 10cm.",
    details: { images: ["/images/mdf/mdf-dog-cutout.png"], weight: "35g", material: "3mm MDF", dimensions: "10cm x 10cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MD" },
    imageUrl: "/images/mdf/mdf-dog-cutout.png" },
  { slug: "mdf-fish-cutout", name: "MDF Fish Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Playful fish silhouette laser-cut from 3mm MDF. Perfect for nautical-themed decor, kids' craft sessions, and ocean-inspired art projects. Smooth edges and flat surface ideal for embellishing. Approximate size: 11cm x 7cm.",
    details: { images: ["/images/mdf/mdf-fish-cutout.png"], weight: "28g", material: "3mm MDF", dimensions: "11cm x 7cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MF" },
    imageUrl: "/images/mdf/mdf-fish-cutout.png" },
  { slug: "mdf-lion-cutout", name: "MDF Lion Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Majestic lion head silhouette cut from 3mm MDF with laser precision. This regal animal cutout is perfect for safari-themed nurseries, motivational wall art, and kids' craft sessions. Approximate size: 11cm x 11cm.",
    details: { images: ["/images/mdf/mdf-lion-cutout.png"], weight: "38g", material: "3mm MDF", dimensions: "11cm x 11cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "ML" },
    imageUrl: "/images/mdf/mdf-lion-cutout.png" },
  { slug: "mdf-owl-cutout", name: "MDF Owl Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Detailed owl silhouette laser-cut from 3mm MDF. This wise little owl features intricate feather details created with precision cutting. Perfect for woodland-themed nurseries and craft projects. Approximate size: 9cm x 12cm.",
    details: { images: ["/images/mdf/mdf-owl-cutout.png"], weight: "38g", material: "3mm MDF", dimensions: "9cm x 12cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MO" },
    imageUrl: "/images/mdf/mdf-owl-cutout.png" },
  { slug: "mdf-turtle-cutout", name: "MDF Turtle Cutout – 3mm Laser Cut", variant: "Good Value", price: 2, category: "MDF Cutouts", stock: 100,
    description: "Cute sea turtle silhouette cut from 3mm MDF using precision laser technology. This tropical cutout is great for beach-themed decor, kids' craft activities, and ocean conservation projects. Approximate size: 10cm x 8cm.",
    details: { images: ["/images/mdf/mdf-turtle-cutout.png"], weight: "30g", material: "3mm MDF", dimensions: "10cm x 8cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MT" },
    imageUrl: "/images/mdf/mdf-turtle-cutout.png" },
  { slug: "mdf-heart-puzzle-5-piece", name: "MDF Heart Puzzle Kit – 5 Piece Set", variant: "Good Value", price: 5, category: "DIY Kits", stock: 100,
    description: "Creative heart puzzle kit featuring 5 interlocking MDF pieces laser-cut from 3mm wood. Kids can paint each piece in different colors and assemble into a beautiful heart wall hanging. Includes hanging string and activity guide. Approximate assembled size: 15cm x 15cm.",
    details: { images: ["/images/mdf/mdf-heart-puzzle-5-piece.png"], weight: "120g", material: "3mm MDF", dimensions: "15cm x 15cm assembled" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MH" },
    imageUrl: "/images/mdf/mdf-heart-puzzle-5-piece.png" },
  { slug: "mdf-rainbow-color-sorting", name: "MDF Rainbow Color Sorting Kit – 7 Piece Educational Set", variant: "Good Value", price: 5, category: "DIY Kits", stock: 100,
    description: "Vibrant rainbow-themed sorting kit with 7 laser-cut 3mm MDF arches in red, orange, yellow, green, blue, indigo, and violet. Stack, nest, and sort by color and size. Perfect for toddler learning, color recognition, and fine motor skill development.",
    details: { images: ["/images/mdf/mdf-rainbow-color-sorting.png"], weight: "140g", material: "3mm MDF", dimensions: "largest arch 15cm x 8cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MR" },
    imageUrl: "/images/mdf/mdf-rainbow-color-sorting.png" },
  { slug: "mdf-star-matching-puzzle", name: "MDF Star Matching Puzzle – 8 Piece Educational Kit", variant: "Good Value", price: 5, category: "DIY Kits", stock: 100,
    description: "Educational star matching puzzle with 8 laser-cut 3mm MDF star pieces in graduated sizes. Kids learn size sorting, color matching, and fine motor skills. Each star is numbered for counting practice. Safe, smooth edges for little hands.",
    details: { images: ["/images/mdf/mdf-star-matching-puzzle.png"], weight: "150g", material: "3mm MDF", dimensions: "stars from 3cm to 12cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MS" },
    imageUrl: "/images/mdf/mdf-star-matching-puzzle.png" },
  { slug: "phone-case-clearance", name: "Phone Case Clearance", variant: "Good Value", price: 5, category: "Clearance", stock: 179,
    description: "Cases for older handsets, clearing the shelf at AED 5 each.\n\nThese are new and still sealed. They fit phones from around 2018 to 2019, including iPhone XS Max, iPhone 11 Pro Max and Samsung S9. The range covers leather flip cases, wallet styles with card slots, and plain protective shells.\n\nTell us your phone model in the order notes and we will match you to what we have in stock. If we cannot match your model we will refund you in full, no quibbling.",
    details: { fits: "Older iPhone and Samsung models, 2018 to 2019", images: ["/images/clearance/phone-case-clearance-0.jpg", "/images/clearance/phone-case-clearance-1.jpg", "/images/clearance/phone-case-clearance-2.jpg", "/images/clearance/phone-case-clearance-3.jpg", "/images/clearance/phone-case-clearance-4.jpg", "/images/clearance/phone-case-clearance-5.jpg"], returns: "Returnable within 7 days, unused", material: "Mixed: leather-look PU, TPU, silicone", condition: "New, sealed in original packaging", collection: "Workshop collection only at this price" },
    imagePlaceholder: { bg: "#6E6862", initials: "PC" },
    imageUrl: "/images/clearance/phone-case-clearance-0.jpg" },
  { slug: "mdf-butterfly-garden-puzzle", name: "MDF Butterfly Garden Puzzle – 8 Piece Set", variant: "Good Value", price: 6, category: "DIY Kits", stock: 100,
    description: "Enchanting butterfly garden puzzle with 8 laser-cut 3mm MDF pieces. Features 4 different butterfly designs and 4 flower shapes that can be mixed and matched. Each piece is ready to paint or use pre-colored. Great for nature-themed crafting.",
    details: { images: ["/images/mdf/mdf-butterfly-garden-puzzle.png"], weight: "160g", material: "3mm MDF", dimensions: "butterflies 10cm each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MB" },
    imageUrl: "/images/mdf/mdf-butterfly-garden-puzzle.png" },
  { slug: "mdf-flower-garden-puzzle", name: "MDF Flower Garden Puzzle – 10 Piece Set", variant: "Good Value", price: 6, category: "DIY Kits", stock: 100,
    description: "Beautiful flower garden puzzle kit with 10 laser-cut 3mm MDF pieces including petals, stems, leaves, and a butterfly. Mix and match to create endless garden scenes on the included base board. Great for imaginative play and fine motor development.",
    details: { images: ["/images/mdf/mdf-flower-garden-puzzle.png"], weight: "180g", material: "3mm MDF", dimensions: "base board 20cm x 15cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MF" },
    imageUrl: "/images/mdf/mdf-flower-garden-puzzle.png" },
  { slug: "mdf-geometric-pattern-puzzle", name: "MDF Geometric Pattern Puzzle – 12 Piece Set", variant: "Good Value", price: 7, category: "DIY Kits", stock: 100,
    description: "Brain-boosting geometric puzzle with 12 laser-cut 3mm MDF shapes including triangles, hexagons, squares, and diamonds. Create tessellations, patterns, and mathematical designs on the included grid board. Develops spatial reasoning and creativity.",
    details: { images: ["/images/mdf/mdf-geometric-pattern-puzzle.png"], weight: "200g", material: "3mm MDF", dimensions: "grid board 20cm x 20cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MG" },
    imageUrl: "/images/mdf/mdf-geometric-pattern-puzzle.png" },
  { slug: "mdf-space-explorer-puzzle", name: "MDF Space Explorer Puzzle – 10 Piece Set", variant: "Good Value", price: 7, category: "DIY Kits", stock: 100,
    description: "Blast off with this space-themed puzzle kit featuring 10 laser-cut 3mm MDF pieces including a rocket, planets, stars, astronaut, and moon. Arrange on the dark blue base board to create your own solar system scene. Educational and fun for aspiring astronauts.",
    details: { images: ["/images/mdf/mdf-space-explorer-puzzle.png"], weight: "220g", material: "3mm MDF", dimensions: "base board 25cm x 20cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MS" },
    imageUrl: "/images/mdf/mdf-space-explorer-puzzle.png" },
  { slug: "mdf-animal-face-paint-kit", name: "Paint Your Own Animal Faces – MDF Kit", variant: "Good Value", price: 8, category: "DIY Kits", stock: 100,
    description: "Fun paint-your-own kit with 6 animal face cutouts laser-cut from 3mm MDF. Includes lion, bear, cat, owl, elephant, and rabbit faces. Comes with 12 non-toxic paint pots, 2 brushes, and googly eyes. Perfect for parties and craft sessions. Each face approximately 10cm.",
    details: { images: ["/images/mdf/mdf-animal-face-paint-kit.png"], weight: "200g", material: "3mm MDF", dimensions: "10cm each face" },
    imagePlaceholder: { bg: "#C9A96E", initials: "PY" },
    imageUrl: "/images/mdf/mdf-animal-face-paint-kit.png" },
  { slug: "mdf-personalized-name-ornament", name: "MDF Personalized Name Ornament – Custom Cut", variant: "Good Value", price: 8, category: "Home Decor", stock: 100,
    description: "Beautifully personalized name ornament laser-cut from 3mm MDF in your choice of script font. Perfect as a door hanger, nursery decoration, or gift tag. Custom cut to order with up to 12 characters. Includes ribbon for hanging. Approximate height: 15cm.",
    details: { images: ["/images/mdf/mdf-personalized-name-ornament.png"], weight: "60g", material: "3mm MDF", dimensions: "15cm x variable width" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MP" },
    imageUrl: "/images/mdf/mdf-personalized-name-ornament.png" },
  { slug: "mdf-spice-jar-labels", name: "MDF Spice Jar Label Set – 30 Piece Kitchen Organizer", variant: "Good Value", price: 8, category: "Home Decor", stock: 100,
    description: "Organize your kitchen with this set of 30 laser-cut 3mm MDF spice jar labels. Each oval label is engraved with common spice names in elegant typography. Self-adhesive backing for easy application. Fits standard spice jar sizes. Includes blank labels for custom spices.",
    details: { images: ["/images/mdf/mdf-spice-jar-labels.png"], weight: "100g", material: "3mm MDF", dimensions: "4cm x 2cm each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MS" },
    imageUrl: "/images/mdf/mdf-spice-jar-labels.png" },
  { slug: "mdf-unicorn-paint-your-own", name: "Paint Your Own Unicorn – MDF Craft Kit", variant: "Good Value", price: 8, category: "DIY Kits", stock: 100,
    description: "Magical unicorn painting kit with a large 3mm MDF unicorn cutout ready to be decorated. Laser-cut with detailed mane and horn outlines. Includes glitter paint, 6 acrylic colors, 2 brushes, and adhesive gemstones. Finished unicorn makes a gorgeous room decoration.",
    details: { images: ["/images/mdf/mdf-unicorn-paint-your-own.png"], weight: "180g", material: "3mm MDF", dimensions: "20cm x 25cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "PY" },
    imageUrl: "/images/mdf/mdf-unicorn-paint-your-own.png" },
  { slug: "mdf-botanical-wall-art", name: "MDF Botanical Wall Art – 3 Piece Leaf Set", variant: "Good Value", price: 10, category: "Home Decor", stock: 100,
    description: "Elegant botanical wall art set with 3 laser-cut 3mm MDF leaf designs: monstera, palm, and fern. Each leaf features intricate vein details cut with precision laser technology. Pre-finished in matte white for a modern Scandinavian look. Sizes range from 20-30cm.",
    details: { images: ["/images/mdf/mdf-botanical-wall-art.png"], weight: "180g", material: "3mm MDF", dimensions: "20-30cm height" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MB" },
    imageUrl: "/images/mdf/mdf-botanical-wall-art.png" },
  { slug: "mdf-dinosaur-paint-set", name: "Paint Your Own Dinosaurs – MDF Kit", variant: "Good Value", price: 10, category: "DIY Kits", stock: 100,
    description: "Roaring fun with this dinosaur painting kit featuring 6 laser-cut 3mm MDF dinosaur silhouettes. Includes T-Rex, Triceratops, Stegosaurus, Pterodactyl, Brachiosaurus, and Velociraptor. Comes with 18 paint colors, 3 brushes, and a display stand. Each dino approximately 12cm.",
    details: { images: ["/images/mdf/mdf-dinosaur-paint-set.png"], weight: "280g", material: "3mm MDF", dimensions: "dinosaurs 12cm each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "PY" },
    imageUrl: "/images/mdf/mdf-dinosaur-paint-set.png" },
  { slug: "mdf-leaf-coaster-set", name: "MDF Leaf Coaster Set – 6 Piece Botanical", variant: "Good Value", price: 10, category: "Home Decor", stock: 100,
    description: "Nature-inspired coaster set with 6 laser-cut 3mm MDF leaf shapes including oak, maple, eucalyptus, palm, monstera, and ginkgo. Each leaf is uniquely shaped and sealed with a waterproof coating. Organic shapes add a natural touch to any table setting.",
    details: { images: ["/images/mdf/mdf-leaf-coaster-set.png"], weight: "120g", material: "3mm MDF", dimensions: "8-12cm each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "ML" },
    imageUrl: "/images/mdf/mdf-leaf-coaster-set.png" },
  { slug: "mdf-mandala-coaster-set", name: "MDF Mandala Coaster Set – 4 Piece", variant: "Good Value", price: 10, category: "Home Decor", stock: 100,
    description: "Exquisite mandala coaster set with 4 laser-cut 3mm MDF coasters featuring intricate geometric patterns. The detailed cutouts create beautiful shadow effects on your table. Sealed with food-safe finish. Each coaster 10cm diameter with cork backing.",
    details: { images: ["/images/mdf/mdf-mandala-coaster-set.png"], weight: "160g", material: "3mm MDF", dimensions: "10cm diameter each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MM" },
    imageUrl: "/images/mdf/mdf-mandala-coaster-set.png" },
  { slug: "mdf-ocean-animals-paint-kit", name: "Paint Your Own Ocean Animals – MDF Kit", variant: "Good Value", price: 10, category: "DIY Kits", stock: 100,
    description: "Dive into creativity with this ocean animal painting kit featuring 8 laser-cut 3mm MDF sea creatures. Includes fish, octopus, dolphin, shark, starfish, seahorse, whale, and crab. Comes with 15 ocean-blue paints, 3 brushes, and an underwater background scene.",
    details: { images: ["/images/mdf/mdf-ocean-animals-paint-kit.png"], weight: "250g", material: "3mm MDF", dimensions: "animals 8-12cm each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "PY" },
    imageUrl: "/images/mdf/mdf-ocean-animals-paint-kit.png" },
  { slug: "mdf-vehicle-paint-set", name: "Paint Your Own Vehicles – MDF Kit", variant: "Good Value", price: 10, category: "DIY Kits", stock: 100,
    description: "On-the-go creativity with this vehicle painting kit featuring 6 laser-cut 3mm MDF transport silhouettes. Includes car, truck, airplane, helicopter, boat, and train. Comes with 15 bright paints, 3 brushes, and a road scene background. Perfect for little motorists.",
    details: { images: ["/images/mdf/mdf-vehicle-paint-set.png"], weight: "250g", material: "3mm MDF", dimensions: "vehicles 10-14cm each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "PY" },
    imageUrl: "/images/mdf/mdf-vehicle-paint-set.png" },
  { slug: "mdf-alphabet-puzzle-board", name: "MDF Alphabet Puzzle Board – 26 Letter Set", variant: "Good Value", price: 12, category: "DIY Kits", stock: 100,
    description: "Complete alphabet learning kit with 26 laser-cut 3mm MDF letters that fit into a matching puzzle board. Each letter is painted a different color for visual learning. Perfect for preschool education, letter recognition, and early spelling. Board size: 30cm x 20cm.",
    details: { images: ["/images/mdf/mdf-alphabet-puzzle-board.png"], weight: "350g", material: "3mm MDF", dimensions: "board 30cm x 20cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MA" },
    imageUrl: "/images/mdf/mdf-alphabet-puzzle-board.png" },
  { slug: "mdf-forest-animal-wall-art", name: "MDF Forest Animal Wall Art – 5 Piece Set", variant: "Good Value", price: 12, category: "Home Decor", stock: 100,
    description: "Charming forest animal wall art set featuring 5 laser-cut 3mm MDF silhouettes: bear, fox, deer, owl, and squirrel. Each piece is painted in natural wood tones and ready to hang. Creates a stunning woodland gallery wall for nurseries and kids' rooms.",
    details: { images: ["/images/mdf/mdf-forest-animal-wall-art.png"], weight: "200g", material: "3mm MDF", dimensions: "animals 8-12cm each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MF" },
    imageUrl: "/images/mdf/mdf-forest-animal-wall-art.png" },
  { slug: "mdf-geometric-ornament-set", name: "MDF Geometric Ornament Set – 6 Piece Holiday Collection", variant: "Good Value", price: 12, category: "Home Decor", stock: 100,
    description: "Modern geometric ornament set with 6 laser-cut 3mm MDF shapes including diamond, sphere frame, cube outline, octahedron, tetrahedron, and icosahedron. Each ornament includes a gold hanging cord. Perfect for minimalist holiday decor or year-round styling.",
    details: { images: ["/images/mdf/mdf-geometric-ornament-set.png"], weight: "120g", material: "3mm MDF", dimensions: "5-8cm each" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MG" },
    imageUrl: "/images/mdf/mdf-geometric-ornament-set.png" },
  { slug: "mdf-geometric-shape-cards", name: "Geometric Shape Learning Cards – MDF Educational Set", variant: "Good Value", price: 12, category: "Kids Toys", stock: 100,
    description: "Hands-on geometry learning set with 10 laser-cut 3mm MDF shape cards and matching wooden pieces. Children explore shapes like star, rectangle, trapezoid, polygon, hexagon, triangle, circle, heart, square, and octagon through play. Perfect for Montessori classrooms and homeschooling.",
    details: { images: ["/images/mdf/mdf-geometric-shape-cards.png"], weight: "280g", material: "3mm MDF", dimensions: "set 16cm x 14cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "GS" },
    imageUrl: "/images/mdf/mdf-geometric-shape-cards.png" },
  { slug: "abc-jigsaw-board", name: "ABC Jigsaw Board", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "The whole alphabet, one piece at a time.\n\nA full A to Z jigsaw board where every letter interlocks with the next. Repetition that never feels like drilling.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/abc-jigsaw-board-0.png", "/images/lasercut/abc-jigsaw-board-1.png", "/images/lasercut/abc-jigsaw-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "196mm x 149mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AB" },
    imageUrl: "/images/lasercut/abc-jigsaw-board-0.png" },
  { slug: "alphabet-car-puzzle", name: "Alphabet Car", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "A to Z, parked in a racing car.\n\nThe whole alphabet cut into the shape of a car, so learning letters comes wrapped in something they already love.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/alphabet-car-puzzle-0.png", "/images/lasercut/alphabet-car-puzzle-1.png", "/images/lasercut/alphabet-car-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AL" },
    imageUrl: "/images/lasercut/alphabet-car-puzzle-0.png" },
  { slug: "alphabet-fish-puzzle", name: "Alphabet Fish", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "A fish with the whole alphabet in its scales.\n\nTwenty-six letter pieces that build into one friendly fish. Take it apart, say the letters, build it back.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/alphabet-fish-puzzle-0.png", "/images/lasercut/alphabet-fish-puzzle-1.png", "/images/lasercut/alphabet-fish-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AL" },
    imageUrl: "/images/lasercut/alphabet-fish-puzzle-0.png" },
  { slug: "alphabet-learning-board", name: "Alphabet Learning Board", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "Letters they can pick up and hold.\n\nEach letter lifts cleanly out of the board. Holding an A is how a child learns the shape of an A.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/alphabet-learning-board-0.png", "/images/lasercut/alphabet-learning-board-1.png", "/images/lasercut/alphabet-learning-board-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AL" },
    imageUrl: "/images/lasercut/alphabet-learning-board-0.png" },
  { slug: "alphabet-snail-puzzle", name: "Alphabet Snail", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "A to Z, spiralling out from the middle.\n\nThe alphabet wound into a snail shell, so the order of the letters is something they can see and follow with a finger.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/alphabet-snail-puzzle-0.png", "/images/lasercut/alphabet-snail-puzzle-1.png", "/images/lasercut/alphabet-snail-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AL" },
    imageUrl: "/images/lasercut/alphabet-snail-puzzle-0.png" },
  { slug: "bear-alphabet-puzzle", name: "Bear Alphabet Puzzle", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "A bear made entirely of letters.\n\nTwenty-six pieces that come together as one friendly bear. The alphabet with a face on it.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/bear-alphabet-puzzle-0.png", "/images/lasercut/bear-alphabet-puzzle-1.png", "/images/lasercut/bear-alphabet-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "BE" },
    imageUrl: "/images/lasercut/bear-alphabet-puzzle-0.png" },
  { slug: "build-a-house-3d-puzzle", name: "Build-a-House 3D Puzzle", variant: "Good Value", price: 15, category: "3D & Architecture", stock: 999,
    description: "Flat pieces in. A house on the shelf out.\n\nSlot-together walls and roof that stand up into a real little house. The first bit of engineering most children ever do.",
    details: { age: "4+", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/build-a-house-3d-puzzle-0.jpg", "/images/lasercut/build-a-house-3d-puzzle-1.jpg", "/images/lasercut/build-a-house-3d-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "BU" },
    imageUrl: "/images/lasercut/build-a-house-3d-puzzle-0.jpg" },
  { slug: "cement-mixer-shape-puzzle", name: "Cement Mixer Shape Puzzle", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "A cement mixer that comes apart and goes back together.\n\nBig friendly pieces in the shape of a working truck. Made for toddlers who want to know how things fit.",
    details: { age: "2-4", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/cement-mixer-shape-puzzle-0.png", "/images/lasercut/cement-mixer-shape-puzzle-1.png", "/images/lasercut/cement-mixer-shape-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CE" },
    imageUrl: "/images/lasercut/cement-mixer-shape-puzzle-0.png" },
  { slug: "colour-me-dinosaur-alphabet-puzzle", name: "Colour-Me Dinosaur Alphabet Puzzle", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "26 pieces. 26 letters. One dinosaur they made themselves.\n\nEvery piece is a letter, and every piece is blank, waiting for them. Build it first, then colour it in. The puzzle they finish twice.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/colour-me-dinosaur-alphabet-puzzle-0.png", "/images/lasercut/colour-me-dinosaur-alphabet-puzzle-1.jpg", "/images/lasercut/colour-me-dinosaur-alphabet-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CO" },
    imageUrl: "/images/lasercut/colour-me-dinosaur-alphabet-puzzle-0.png" },
  { slug: "count-and-match-number-board", name: "Count & Match Number Board", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "The puzzle that teaches counting before they can read.\n\nTen hand-cut pieces pair each numeral with the dots that match it, so little fingers feel the difference between three and eight before they can say it. Cut and sanded to order in our workshop, edges smoothed by hand.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/count-and-match-number-board-0.png", "/images/lasercut/count-and-match-number-board-1.png", "/images/lasercut/count-and-match-number-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 200mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CO" },
    imageUrl: "/images/lasercut/count-and-match-number-board-0.png" },
  { slug: "counting-hands-board-1", name: "Counting Hands Board", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Counting on your fingers, made out of wood.\n\nTwo hands, ten fingers, and the number that goes with each. The oldest counting method there is, turned into a puzzle.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/counting-hands-board-1-0.jpg", "/images/lasercut/counting-hands-board-1-1.jpg", "/images/lasercut/counting-hands-board-1-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CO" },
    imageUrl: "/images/lasercut/counting-hands-board-1-0.jpg" },
  { slug: "counting-hands-board-2", name: "Counting Hands Board, Second Design", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Ten fingers, ten numbers, one board.\n\nA second take on the counting hands, with its own layout. Match the number to the fingers held up and it clicks into place.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/counting-hands-board-2-0.jpg", "/images/lasercut/counting-hands-board-2-1.jpg", "/images/lasercut/counting-hands-board-2-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CO" },
    imageUrl: "/images/lasercut/counting-hands-board-2-0.jpg" },
  { slug: "duck-shape-board", name: "Duck Shape Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "One duck. A handful of pieces. A very proud toddler.\n\nA simple, generous puzzle for the very beginning. Few enough pieces to finish, satisfying enough to do again.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/duck-shape-board-0.jpg", "/images/lasercut/duck-shape-board-1.jpg", "/images/lasercut/duck-shape-board-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "DU" },
    imageUrl: "/images/lasercut/duck-shape-board-0.jpg" },
  { slug: "elephant-number-puzzle", name: "Elephant Number Puzzle", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Numbers that add up to an elephant.\n\nEach numbered piece interlocks into the shape of an elephant. Counting practice with a reward at the end.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/elephant-number-puzzle-0.png", "/images/lasercut/elephant-number-puzzle-1.png", "/images/lasercut/elephant-number-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "EL" },
    imageUrl: "/images/lasercut/elephant-number-puzzle-0.png" },
  { slug: "excavator-puzzle", name: "Excavator Puzzle", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "The digger, in pieces, on the floor, again.\n\nA digger that comes apart at the arm, bucket and cab. For the child who wants to know how the machine works.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/excavator-puzzle-0.png", "/images/lasercut/excavator-puzzle-1.png", "/images/lasercut/excavator-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "EX" },
    imageUrl: "/images/lasercut/excavator-puzzle-0.png" },
  { slug: "farmyard-animal-board", name: "Farmyard Animal Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Every animal has its own place to go home to.\n\nA board of animal cutouts where each shape fits one space and one space only. Simple, satisfying, endlessly repeatable.",
    details: { age: "2-4", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/farmyard-animal-board-0.jpg", "/images/lasercut/farmyard-animal-board-1.jpg", "/images/lasercut/farmyard-animal-board-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "FA" },
    imageUrl: "/images/lasercut/farmyard-animal-board-0.jpg" },
  { slug: "first-animals-peg-board", name: "First Animals Peg Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Chunky pegs made for hands that are still learning to grip.\n\nEach animal lifts out by a wooden peg sized for a toddler pincer grip. The first puzzle most children ever finish on their own.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/first-animals-peg-board-0.jpg", "/images/lasercut/first-animals-peg-board-1.jpg", "/images/lasercut/first-animals-peg-board-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "FI" },
    imageUrl: "/images/lasercut/first-animals-peg-board-0.jpg" },
  { slug: "geometric-shape-board", name: "Geometric Shape Board", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "Circle, square, triangle. One home each.\n\nThe classic Montessori shape board, cut clean so each piece drops in with a satisfying fit. Where shape recognition starts.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/geometric-shape-board-0.jpg", "/images/lasercut/geometric-shape-board-1.jpg", "/images/lasercut/geometric-shape-board-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "GE" },
    imageUrl: "/images/lasercut/geometric-shape-board-0.jpg" },
  { slug: "giraffe-number-puzzle", name: "Giraffe Number Puzzle", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "The tallest way to count to ten.\n\nNumbered pieces stacked up a giraffe's neck, so the counting goes the same way the animal does. Up.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/giraffe-number-puzzle-0.png", "/images/lasercut/giraffe-number-puzzle-1.png", "/images/lasercut/giraffe-number-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "GI" },
    imageUrl: "/images/lasercut/giraffe-number-puzzle-0.png" },
  { slug: "heart-tangram-nine-pieces", name: "Heart Tangram", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "One heart. Nine pieces. Hundreds of ways to put it back.\n\nThe classic tangram cut into a heart, so it stays beautiful even when it is finished and sitting on the shelf. Quiet play that grows with them.",
    details: { age: "4+", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/heart-tangram-nine-pieces-0.png", "/images/lasercut/heart-tangram-nine-pieces-1.png", "/images/lasercut/heart-tangram-nine-pieces-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "HE" },
    imageUrl: "/images/lasercut/heart-tangram-nine-pieces-0.png" },
  { slug: "little-builders-tool-set-puzzle", name: "Little Builders Tool Set", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "A toolbox where every tool is a puzzle piece.\n\nHammer, saw, spanner and screwdriver, each cut to lift out of its own slot. Pretend play and shape matching in the same board.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/little-builders-tool-set-puzzle-0.jpg", "/images/lasercut/little-builders-tool-set-puzzle-1.jpg", "/images/lasercut/little-builders-tool-set-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "LI" },
    imageUrl: "/images/lasercut/little-builders-tool-set-puzzle-0.jpg" },
  { slug: "mdf-3d-butterfly-building-kit", name: "MDF 3D Butterfly Building Kit – Premium Set", variant: "Good Value", price: 15, category: "DIY Kits", stock: 100,
    description: "Stunning 3D butterfly construction kit with 20 laser-cut 3mm MDF pieces. Build realistic three-dimensional butterflies using the interlocking slot design. No glue needed! Includes 3 butterfly templates in different sizes and a display branch. A premium craft experience.",
    details: { images: ["/images/mdf/mdf-3d-butterfly-building-kit.png"], weight: "200g", material: "3mm MDF", dimensions: "finished butterflies 8-15cm wingspan" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MD" },
    imageUrl: "/images/mdf/mdf-3d-butterfly-building-kit.png" },
  { slug: "mdf-3d-dinosaur-building-kit", name: "MDF 3D Dinosaur Building Kit – Premium Set", variant: "Good Value", price: 15, category: "DIY Kits", stock: 100,
    description: "Epic 3D dinosaur building kit with 25 laser-cut 3mm MDF pieces. Construct a T-Rex skeleton using precision-cut interlocking joints. No glue or tools required. Includes illustrated assembly guide and fun dinosaur facts card. Perfect for young paleontologists.",
    details: { images: ["/images/mdf/mdf-3d-dinosaur-building-kit.png"], weight: "250g", material: "3mm MDF", dimensions: "assembled T-Rex 20cm tall" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MD" },
    imageUrl: "/images/mdf/mdf-3d-dinosaur-building-kit.png" },
  { slug: "mdf-arabic-calligraphy-art", name: "MDF Arabic Calligraphy Wall Art – Bismillah", variant: "Good Value", price: 15, category: "Home Decor", stock: 100,
    description: "Stunning Arabic calligraphy wall art laser-cut from 3mm MDF. Features the word 'Bismillah' in elegant Thuluth script with decorative border frame. Precision laser cutting captures every delicate curve. Available in gold, black, or white finish. Dimensions: 25cm x 15cm.",
    details: { images: ["/images/mdf/mdf-arabic-calligraphy-art.png"], weight: "150g", material: "3mm MDF", dimensions: "25cm x 15cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MA" },
    imageUrl: "/images/mdf/mdf-arabic-calligraphy-art.png" },
  { slug: "mdf-fish-number-puzzle", name: "MDF Fish Number Puzzle – 12 Piece Educational Toy", variant: "Good Value", price: 15, category: "Kids Toys", stock: 100,
    description: "Engaging fish-shaped number puzzle with 12 laser-cut 3mm MDF pieces numbered 0-10. Children learn counting and number sequencing while developing fine motor skills. Each piece has a unique jigsaw interlock. Natural wood finish ready for painting. Assembled size: 25cm x 12cm.",
    details: { images: ["/images/mdf/mdf-fish-number-puzzle.png"], weight: "180g", material: "3mm MDF", dimensions: "25cm x 12cm assembled" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MF" },
    imageUrl: "/images/mdf/mdf-fish-number-puzzle.png" },
  { slug: "mdf-moon-phase-wall-hanging", name: "MDF Moon Phase Wall Hanging – 7 Piece Set", variant: "Good Value", price: 15, category: "Home Decor", stock: 100,
    description: "Celestial moon phase wall hanging with 7 laser-cut 3mm MDF moon shapes from new moon to full moon and back. Connected with natural jute twine on a wooden dowel. Bohemian decor piece perfect for bedrooms and meditation spaces. Total width: 60cm.",
    details: { images: ["/images/mdf/mdf-moon-phase-wall-hanging.png"], weight: "200g", material: "3mm MDF", dimensions: "60cm wide x 25cm tall" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MM" },
    imageUrl: "/images/mdf/mdf-moon-phase-wall-hanging.png" },
  { slug: "mdf-shape-sorter-puzzle", name: "MDF Shape Sorter Puzzle – Toddler Educational Toy", variant: "Good Value", price: 15, category: "Kids Toys", stock: 100,
    description: "Classic shape sorting toy reimagined in laser-cut 3mm MDF. Features a sturdy base board with cutouts for 8 different shapes: circle, square, triangle, heart, star, hexagon, diamond, and cross. Each shape is colored for matching. Perfect for ages 2-4 developing fine motor skills.",
    details: { images: ["/images/mdf/mdf-shape-sorter-puzzle.png"], weight: "350g", material: "3mm MDF", dimensions: "board 20cm x 20cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MS" },
    imageUrl: "/images/mdf/mdf-shape-sorter-puzzle.png" },
  { slug: "mdf-tangram-puzzle-set", name: "MDF Tangram Puzzle Set – Classic Brain Teaser", variant: "Good Value", price: 15, category: "Kids Toys", stock: 100,
    description: "Traditional tangram puzzle made from premium laser-cut 3mm MDF. Includes 7 tangram pieces in vibrant colors that fit into a square base tray. Comes with 20 pattern cards showing different shapes to create: animals, people, vehicles, and more. Develops geometry and spatial reasoning.",
    details: { images: ["/images/mdf/mdf-tangram-puzzle-set.png"], weight: "200g", material: "3mm MDF", dimensions: "tray 15cm x 15cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MT" },
    imageUrl: "/images/mdf/mdf-tangram-puzzle-set.png" },
  { slug: "montessori-3d-layer-puzzle", name: "Montessori Layered Puzzle", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "Every layer is a step further in.\n\nA stacked Montessori puzzle where each level sits inside the one below. Depth, order and sequence in one object.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/montessori-3d-layer-puzzle-0.png", "/images/lasercut/montessori-3d-layer-puzzle-1.png", "/images/lasercut/montessori-3d-layer-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MO" },
    imageUrl: "/images/lasercut/montessori-3d-layer-puzzle-0.png" },
  { slug: "number-maths-peg-board", name: "Number Maths Peg Board", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Numbers with handles.\n\nA pegged number board built for the age where everything gets picked up, turned over, and put somewhere else.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/number-maths-peg-board-0.jpg", "/images/lasercut/number-maths-peg-board-1.jpg", "/images/lasercut/number-maths-peg-board-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "NU" },
    imageUrl: "/images/lasercut/number-maths-peg-board-0.jpg" },
  { slug: "owl-number-tower-puzzle", name: "Owl Number Tower", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "An owl that stacks itself, one number at a time.\n\nEach layer is a numbered piece, so the tower only stands when the counting is right. Stands up on the shelf when they are done.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/owl-number-tower-puzzle-0.png", "/images/lasercut/owl-number-tower-puzzle-1.png", "/images/lasercut/owl-number-tower-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "OW" },
    imageUrl: "/images/lasercut/owl-number-tower-puzzle-0.png" },
  { slug: "rocket-number-puzzle", name: "Rocket Number Puzzle", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Count down from ten, then launch.\n\nA rocket built from numbered pieces, so the countdown is the puzzle. Preschool maths with somewhere to go.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/rocket-number-puzzle-0.png", "/images/lasercut/rocket-number-puzzle-1.jpg", "/images/lasercut/rocket-number-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "RO" },
    imageUrl: "/images/lasercut/rocket-number-puzzle-0.png" },
  { slug: "sea-creatures-peg-board", name: "Sea Creatures Peg Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Fish, crab, octopus, turtle. All out by the peg.\n\nA rock-pool board with wooden pegs on every creature. Naming, matching and gripping, all in one.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/sea-creatures-peg-board-0.jpg", "/images/lasercut/sea-creatures-peg-board-1.jpg", "/images/lasercut/sea-creatures-peg-board-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "SE" },
    imageUrl: "/images/lasercut/sea-creatures-peg-board-0.jpg" },
  { slug: "shape-peg-board", name: "Shape Peg Board", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "The very first shapes, on very easy pegs.\n\nBasic shapes with chunky wooden pegs. Where a toddler learns that things have a right way round.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/shape-peg-board-0.png", "/images/lasercut/shape-peg-board-1.png", "/images/lasercut/shape-peg-board-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "SH" },
    imageUrl: "/images/lasercut/shape-peg-board-0.png" },
  { slug: "shape-stencil-set", name: "Shape Stencil Set", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "Trace it, draw it, learn it.\n\nCut-out shape stencils for tracing onto paper. The bridge between recognising a shape and being able to draw one.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/shape-stencil-set-0.jpg", "/images/lasercut/shape-stencil-set-1.jpg", "/images/lasercut/shape-stencil-set-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "SH" },
    imageUrl: "/images/lasercut/shape-stencil-set-0.jpg" },
  { slug: "solar-system-peg-puzzle", name: "Solar System Peg Puzzle", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Eight planets, in the right order, every time.\n\nEach planet lifts out on its own peg and only fits its own orbit. The solar system small enough to hold.",
    details: { age: "4+", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/solar-system-peg-puzzle-0.png", "/images/lasercut/solar-system-peg-puzzle-1.jpg", "/images/lasercut/solar-system-peg-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "SO" },
    imageUrl: "/images/lasercut/solar-system-peg-puzzle-0.png" },
  { slug: "stacking-animal-friends-3d", name: "Stacking Animal Friends", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Flat pieces that stand up into animals.\n\nSlot the pieces together and the puzzle becomes a creature that stands on its own. The moment it stops being flat is the moment they get hooked.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/stacking-animal-friends-3d-0.png", "/images/lasercut/stacking-animal-friends-3d-1.png", "/images/lasercut/stacking-animal-friends-3d-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "ST" },
    imageUrl: "/images/lasercut/stacking-animal-friends-3d-0.png" },
  { slug: "teddy-bear-layer-board", name: "Teddy Bear Layer Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "A bear that builds up in layers.\n\nStacked pieces that turn a flat board into a bear with depth. Soft shapes, rounded edges, made for small hands.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/teddy-bear-layer-board-0.png", "/images/lasercut/teddy-bear-layer-board-1.png", "/images/lasercut/teddy-bear-layer-board-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TE" },
    imageUrl: "/images/lasercut/teddy-bear-layer-board-0.png" },
  { slug: "toddler-alphabet-board", name: "Toddler Alphabet Board", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "Bigger letters, for smaller hands.\n\nA chunkier alphabet board sized for toddlers who are not ready for small pieces yet. Same letters, easier grip.",
    details: { age: "2-4", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/toddler-alphabet-board-0.png", "/images/lasercut/toddler-alphabet-board-1.png", "/images/lasercut/toddler-alphabet-board-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TO" },
    imageUrl: "/images/lasercut/toddler-alphabet-board-0.png" },
  { slug: "tractor-shape-puzzle", name: "Tractor Shape Puzzle", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "The tractor that teaches shapes on the way past.\n\nWheels, cab and trailer each lift out as their own shape. Ready to paint if you want it in your own colours.",
    details: { age: "2-4", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/tractor-shape-puzzle-0.png", "/images/lasercut/tractor-shape-puzzle-1.png", "/images/lasercut/tractor-shape-puzzle-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/tractor-shape-puzzle-0.png" },
  { slug: "truck-peg-puzzle-1", name: "Truck Peg Puzzle, Design One", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "A truck built from shapes.\n\nEach part of the truck is a shape, and each shape lifts out on a peg. Two lessons in one small board.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-1-0.png", "/images/lasercut/truck-peg-puzzle-1-1.png", "/images/lasercut/truck-peg-puzzle-1-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-1-0.png" },
  { slug: "truck-peg-puzzle-2", name: "Truck Peg Puzzle, Design Two", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Another truck, another set of shapes.\n\nA second design in the truck peg series, with its own shape layout. Collect the set or pick a favourite.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-2-0.png", "/images/lasercut/truck-peg-puzzle-2-1.png", "/images/lasercut/truck-peg-puzzle-2-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-2-0.png" },
  { slug: "truck-peg-puzzle-3", name: "Truck Peg Puzzle, Design Three", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Shapes that drive.\n\nChunky pegged pieces that build a working-looking truck. Sized for the youngest puzzle age.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-3-0.png", "/images/lasercut/truck-peg-puzzle-3-1.png", "/images/lasercut/truck-peg-puzzle-3-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-3-0.png" },
  { slug: "truck-peg-puzzle-4", name: "Truck Peg Puzzle, Design Four", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Lift it, name it, put it back.\n\nA peg truck board with a different silhouette again. The repetition is the point at this age.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-4-0.png", "/images/lasercut/truck-peg-puzzle-4-1.png", "/images/lasercut/truck-peg-puzzle-4-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-4-0.png" },
  { slug: "truck-peg-puzzle-5", name: "Truck Peg Puzzle, Design Five", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Big pegs, small hands, one truck.\n\nAnother in the toddler truck series. Simple shapes, generous pieces, nothing to lose under the sofa.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-5-0.png", "/images/lasercut/truck-peg-puzzle-5-1.png", "/images/lasercut/truck-peg-puzzle-5-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-5-0.png" },
  { slug: "truck-peg-puzzle-6", name: "Truck Peg Puzzle, Design Six", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "The last truck in the set.\n\nSixth design in the peg truck range. Same easy pegs, same satisfying fit, a different shape to learn.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-6-0.jpg", "/images/lasercut/truck-peg-puzzle-6-1.jpg", "/images/lasercut/truck-peg-puzzle-6-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-6-0.jpg" },
  { slug: "vehicles-peg-board", name: "Vehicles Peg Board", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Car, bus, boat, plane. Lift and learn.\n\nChunky pegged vehicles for the youngest hands. Naming things is half the play, fitting them is the other half.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/vehicles-peg-board-0.png", "/images/lasercut/vehicles-peg-board-1.png", "/images/lasercut/vehicles-peg-board-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "VE" },
    imageUrl: "/images/lasercut/vehicles-peg-board-0.png" },
  { slug: "watermelon-maths-game", name: "Watermelon Maths Game", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Slice the watermelon, solve the sum.\n\nA fruit that comes apart into maths. Halves, quarters and simple sums, in a shape that makes fractions obvious.",
    details: { age: "4+", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/watermelon-maths-game-0.png", "/images/lasercut/watermelon-maths-game-1.png", "/images/lasercut/watermelon-maths-game-2.png"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "WA" },
    imageUrl: "/images/lasercut/watermelon-maths-game-0.png" },
  { slug: "mdf-honeycomb-shelf-set", name: "MDF Honeycomb Shelf Set – 3 Piece Wall Display", variant: "Good Value", price: 18, category: "Home Decor", stock: 100,
    description: "Trendy honeycomb shelf set with 3 hexagonal laser-cut 3mm MDF frames. Arrange in any configuration to create a unique wall display. Perfect for displaying small plants, photos, and trinkets. Easy wall mounting with included hardware. Each hexagon 15cm across.",
    details: { images: ["/images/mdf/mdf-honeycomb-shelf-set.png"], weight: "250g", material: "3mm MDF", dimensions: "15cm per hexagon" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MH" },
    imageUrl: "/images/mdf/mdf-honeycomb-shelf-set.png" },
  { slug: "mdf-counting-abc-board", name: "MDF Counting & ABC Learning Board – Educational Toy", variant: "Good Value", price: 20, category: "Kids Toys", stock: 100,
    description: "Comprehensive learning board with 36 laser-cut 3mm MDF pieces. Features 26 alphabet letters and 10 numbered tiles that slot into a beautifully designed base board. Double-sided: letters on one side, numbers on the other. Develops literacy and numeracy skills. Board: 35cm x 25cm.",
    details: { images: ["/images/mdf/mdf-counting-abc-board.png"], weight: "500g", material: "3mm MDF", dimensions: "board 35cm x 25cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MC" },
    imageUrl: "/images/mdf/mdf-counting-abc-board.png" },
  { slug: "mdf-tree-of-life", name: "MDF Tree of Life Wall Art – 3mm Laser Cut", variant: "Good Value", price: 20, category: "Home Decor", stock: 100,
    description: "Elegant laser-cut 3mm MDF Tree of Life wall art featuring an intricate silhouette of branches, trunk, and roots. A timeless decorative piece for living rooms, bedrooms, or meditation spaces. Natural wood finish ready for painting, staining, or leaving as-is. Size: 30cm x 40cm.",
    details: { images: ["/images/mdf/mdf-tree-of-life.png"], weight: "320g", material: "3mm MDF", dimensions: "30cm x 40cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MT" },
    imageUrl: "/images/mdf/mdf-tree-of-life.png" },
  { slug: "mdf-3d-city-building-set", name: "MDF 3D City Building Set – Premium Construction Kit", variant: "Good Value", price: 25, category: "Kids Toys", stock: 100,
    description: "Amazing 3D city building set with 40+ laser-cut 3mm MDF pieces. Construct houses, a school, a hospital, trees, cars, and road sections into a complete miniature city. Interlocking design requires no glue. Develops engineering thinking and spatial awareness. Finished city fits on a tabletop.",
    details: { images: ["/images/mdf/mdf-3d-city-building-set.png"], weight: "600g", material: "3mm MDF", dimensions: "assembled city 30cm x 30cm" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MD" },
    imageUrl: "/images/mdf/mdf-3d-city-building-set.png" },
  { slug: "mdf-marble-run-contraption", name: "MDF Marble Run Contraption – STEM Building Set", variant: "Good Value", price: 25, category: "Kids Toys", stock: 100,
    description: "Exciting STEM marble run set with 30 laser-cut 3mm MDF tracks, ramps, funnels, and supports. Build endless marble run configurations and watch marbles race through your creation. Develops physics understanding, problem-solving, and engineering skills. Includes 5 glass marbles.",
    details: { images: ["/images/mdf/mdf-marble-run-contraption.png"], weight: "450g", material: "3mm MDF", dimensions: "builds up to 40cm tall" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MM" },
    imageUrl: "/images/mdf/mdf-marble-run-contraption.png" },
]

export function getProductBySlug(slug: string): Product | undefined { return products.find((p) => p.slug === slug && !p.hidden); }
export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return products.filter((p) => !p.hidden);
  return products.filter((p) => p.category === category && !p.hidden);
}
export function formatPrice(price: number): string { return "AED " + price.toString(); }
export function calculateSubtotal(items: { product: Product; quantity: number }[]): number {
  return items.reduce((sum, item) => sum + item.product.price * item.quantity, 0);
}

// The hidden flag stays in the type because the storefront filters on it.
// Hidden categories simply aren't emitted (no visible products in Postgres),
// so the flag is always undefined here — the filters still compile and pass.
export interface Category { name: string; description: string; icon: string; hidden?: boolean; }

export const categories: Category[] = [
  { name: "MDF Cutouts", description: "20 products", icon: "🪵" },
  { name: "DIY Kits", description: "15 products", icon: "🎨" },
  { name: "Home Decor", description: "11 products", icon: "📦" },
  { name: "Vehicles & Making", description: "11 products", icon: "📦" },
  { name: "Numbers & Counting", description: "9 products", icon: "📦" },
  { name: "Alphabet & Literacy", description: "8 products", icon: "📦" },
  { name: "Kids Toys", description: "7 products", icon: "🧸" },
  { name: "Animals & Nature", description: "7 products", icon: "📦" },
  { name: "Shapes & Montessori", description: "5 products", icon: "📦" },
  { name: "Clearance", description: "1 products", icon: "📦" },
  { name: "3D & Architecture", description: "1 products", icon: "📦" },
]
