// AUTO-GENERATED FROM POSTGRES — DO NOT EDIT BY HAND.
// Source of truth: the `products` table in the self-hosted Postgres.
// Regenerate:  node scripts/catalog/04-generate-catalog.mjs
// Generated:   2026-08-08T19:06:50.292Z  (41 products)

export interface Product {
  slug: string; name: string; variant: string; price: number;
  category: string;
  stock: number; description: string;
  // The details object maps to a jsonb column, so its shape is open by design.
  // Named keys are the ones the UI reads; the index signature stops every new
  // attribute (fits, condition, returns and so on) from being a type error.
  details: {
    dimensions?: string; material?: string; care?: string; weight?: string; packWeight?: string;
    age?: string; made?: string; personalisation?: string; images?: string[];
    [key: string]: string | string[] | undefined;
  };
  imagePlaceholder: { bg: string; initials: string; };
  imageUrl: string; cjPid?: string; cjPrice?: string;
  hidden?: boolean;
}

export const products: Product[] = [
  { slug: "abc-jigsaw-board", name: "ABC Jigsaw Board", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "The whole alphabet, one piece at a time.\n\nA full A to Z jigsaw board where every letter interlocks with the next. Repetition that never feels like drilling.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/abc-jigsaw-board-0.png", "/images/lasercut/abc-jigsaw-board-1.png", "/images/lasercut/abc-jigsaw-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "196mm x 149mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AB" },
    imageUrl: "/images/lasercut/abc-jigsaw-board-0.png" },
  { slug: "alphabet-car-puzzle", name: "Alphabet Car", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "A to Z, parked in a racing car.\n\nThe whole alphabet cut into the shape of a car, so learning letters comes wrapped in something they already love.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/alphabet-car-puzzle-0.png", "/images/lasercut/alphabet-car-puzzle-1.png", "/images/lasercut/alphabet-car-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "190mm x 103mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AL" },
    imageUrl: "/images/lasercut/alphabet-car-puzzle-0.png" },
  { slug: "alphabet-fish-puzzle", name: "Alphabet Fish", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "A fish with the whole alphabet in its scales.\n\nTwenty-six letter pieces that build into one friendly fish. Take it apart, say the letters, build it back.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/alphabet-fish-puzzle-0.png", "/images/lasercut/alphabet-fish-puzzle-1.png", "/images/lasercut/alphabet-fish-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "195mm x 130mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AL" },
    imageUrl: "/images/lasercut/alphabet-fish-puzzle-0.png" },
  { slug: "alphabet-learning-board", name: "Alphabet Learning Board", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "Letters they can pick up and hold.\n\nEach letter lifts cleanly out of the board. Holding an A is how a child learns the shape of an A.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/alphabet-learning-board-0.png", "/images/lasercut/alphabet-learning-board-1.png", "/images/lasercut/alphabet-learning-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "190mm x 171mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AL" },
    imageUrl: "/images/lasercut/alphabet-learning-board-0.png" },
  { slug: "alphabet-snail-puzzle", name: "Alphabet Snail", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "A to Z, spiralling out from the middle.\n\nThe alphabet wound into a snail shell, so the order of the letters is something they can see and follow with a finger.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/alphabet-snail-puzzle-0.png", "/images/lasercut/alphabet-snail-puzzle-1.png", "/images/lasercut/alphabet-snail-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "196mm x 155mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "AL" },
    imageUrl: "/images/lasercut/alphabet-snail-puzzle-0.png" },
  { slug: "bear-alphabet-puzzle", name: "Bear Alphabet Puzzle", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "A bear made entirely of letters.\n\nTwenty-six pieces that come together as one friendly bear. The alphabet with a face on it.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/bear-alphabet-puzzle-0.png", "/images/lasercut/bear-alphabet-puzzle-1.png", "/images/lasercut/bear-alphabet-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "148mm x 196mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "BE" },
    imageUrl: "/images/lasercut/bear-alphabet-puzzle-0.png" },
  { slug: "build-a-house-3d-puzzle", name: "Build-a-House 3D Puzzle", variant: "Good Value", price: 15, category: "3D & Architecture", stock: 999,
    description: "Flat pieces in. A house on the shelf out.\n\nSlot-together walls and roof that stand up into a real little house. The first bit of engineering most children ever do.",
    details: { age: "4+", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/build-a-house-3d-puzzle-0.jpg", "/images/lasercut/build-a-house-3d-puzzle-1.jpg", "/images/lasercut/build-a-house-3d-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 156mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "BU" },
    imageUrl: "/images/lasercut/build-a-house-3d-puzzle-0.jpg" },
  { slug: "cement-mixer-shape-puzzle", name: "Cement Mixer Shape Puzzle", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "A cement mixer that comes apart and goes back together.\n\nBig friendly pieces in the shape of a working truck. Made for toddlers who want to know how things fit.",
    details: { age: "2-4", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/cement-mixer-shape-puzzle-0.png", "/images/lasercut/cement-mixer-shape-puzzle-1.png", "/images/lasercut/cement-mixer-shape-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "175mm x 200mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CE" },
    imageUrl: "/images/lasercut/cement-mixer-shape-puzzle-0.png" },
  { slug: "colour-me-dinosaur-alphabet-puzzle", name: "Colour-Me Dinosaur Alphabet Puzzle", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "26 pieces. 26 letters. One dinosaur they made themselves.\n\nEvery piece is a letter, and every piece is blank, waiting for them. Build it first, then colour it in. The puzzle they finish twice.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/colour-me-dinosaur-alphabet-puzzle-0.png", "/images/lasercut/colour-me-dinosaur-alphabet-puzzle-1.jpg", "/images/lasercut/colour-me-dinosaur-alphabet-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 185mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CO" },
    imageUrl: "/images/lasercut/colour-me-dinosaur-alphabet-puzzle-0.png" },
  { slug: "count-and-match-number-board", name: "Count & Match Number Board", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "The puzzle that teaches counting before they can read.\n\nTen hand-cut pieces pair each numeral with the dots that match it, so little fingers feel the difference between three and eight before they can say it. Cut and sanded to order in our workshop, edges smoothed by hand.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/count-and-match-number-board-0.png", "/images/lasercut/count-and-match-number-board-1.png", "/images/lasercut/count-and-match-number-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 200mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CO" },
    imageUrl: "/images/lasercut/count-and-match-number-board-0.png" },
  { slug: "counting-hands-board-1", name: "Counting Hands Board", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Counting on your fingers, made out of wood.\n\nTwo hands, ten fingers, and the number that goes with each. The oldest counting method there is, turned into a puzzle.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/counting-hands-board-1-0.jpg", "/images/lasercut/counting-hands-board-1-1.jpg", "/images/lasercut/counting-hands-board-1-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "200mm x 106mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CO" },
    imageUrl: "/images/lasercut/counting-hands-board-1-0.jpg" },
  { slug: "counting-hands-board-2", name: "Counting Hands Board, Second Design", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Ten fingers, ten numbers, one board.\n\nA second take on the counting hands, with its own layout. Match the number to the fingers held up and it clicks into place.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/counting-hands-board-2-0.jpg", "/images/lasercut/counting-hands-board-2-1.jpg", "/images/lasercut/counting-hands-board-2-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "200mm x 106mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "CO" },
    imageUrl: "/images/lasercut/counting-hands-board-2-0.jpg" },
  { slug: "duck-shape-board", name: "Duck Shape Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "One duck. A handful of pieces. A very proud toddler.\n\nA simple, generous puzzle for the very beginning. Few enough pieces to finish, satisfying enough to do again.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/duck-shape-board-0.jpg", "/images/lasercut/duck-shape-board-1.jpg", "/images/lasercut/duck-shape-board-2.jpg"], material: "3mm MDF, sanded by hand", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "DU" },
    imageUrl: "/images/lasercut/duck-shape-board-0.jpg" },
  { slug: "elephant-number-puzzle", name: "Elephant Number Puzzle", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Numbers that add up to an elephant.\n\nEach numbered piece interlocks into the shape of an elephant. Counting practice with a reward at the end.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/elephant-number-puzzle-0.png", "/images/lasercut/elephant-number-puzzle-1.png", "/images/lasercut/elephant-number-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "190mm x 133mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "EL" },
    imageUrl: "/images/lasercut/elephant-number-puzzle-0.png" },
  { slug: "excavator-puzzle", name: "Excavator Puzzle", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "The digger, in pieces, on the floor, again.\n\nA digger that comes apart at the arm, bucket and cab. For the child who wants to know how the machine works.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/excavator-puzzle-0.png", "/images/lasercut/excavator-puzzle-1.png", "/images/lasercut/excavator-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "201mm x 175mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "EX" },
    imageUrl: "/images/lasercut/excavator-puzzle-0.png" },
  { slug: "farmyard-animal-board", name: "Farmyard Animal Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Every animal has its own place to go home to.\n\nA board of animal cutouts where each shape fits one space and one space only. Simple, satisfying, endlessly repeatable.",
    details: { age: "2-4", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/farmyard-animal-board-0.jpg", "/images/lasercut/farmyard-animal-board-1.jpg", "/images/lasercut/farmyard-animal-board-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "157mm x 200mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "FA" },
    imageUrl: "/images/lasercut/farmyard-animal-board-0.jpg" },
  { slug: "first-animals-peg-board", name: "First Animals Peg Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Chunky pegs made for hands that are still learning to grip.\n\nEach animal lifts out by a wooden peg sized for a toddler pincer grip. The first puzzle most children ever finish on their own.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/first-animals-peg-board-0.jpg", "/images/lasercut/first-animals-peg-board-1.jpg", "/images/lasercut/first-animals-peg-board-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "183mm x 132mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "FI" },
    imageUrl: "/images/lasercut/first-animals-peg-board-0.jpg" },
  { slug: "geometric-shape-board", name: "Geometric Shape Board", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "Circle, square, triangle. One home each.\n\nThe classic Montessori shape board, cut clean so each piece drops in with a satisfying fit. Where shape recognition starts.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/geometric-shape-board-0.jpg", "/images/lasercut/geometric-shape-board-1.jpg", "/images/lasercut/geometric-shape-board-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "198mm x 192mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "GE" },
    imageUrl: "/images/lasercut/geometric-shape-board-0.jpg" },
  { slug: "giraffe-number-puzzle", name: "Giraffe Number Puzzle", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "The tallest way to count to ten.\n\nNumbered pieces stacked up a giraffe's neck, so the counting goes the same way the animal does. Up.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/giraffe-number-puzzle-0.png", "/images/lasercut/giraffe-number-puzzle-1.png", "/images/lasercut/giraffe-number-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "93mm x 201mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "GI" },
    imageUrl: "/images/lasercut/giraffe-number-puzzle-0.png" },
  { slug: "heart-tangram-nine-pieces", name: "Heart Tangram", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "One heart. Nine pieces. Hundreds of ways to put it back.\n\nThe classic tangram cut into a heart, so it stays beautiful even when it is finished and sitting on the shelf. Quiet play that grows with them.",
    details: { age: "4+", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/heart-tangram-nine-pieces-0.png", "/images/lasercut/heart-tangram-nine-pieces-1.png", "/images/lasercut/heart-tangram-nine-pieces-2.png"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 130mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "HE" },
    imageUrl: "/images/lasercut/heart-tangram-nine-pieces-0.png" },
  { slug: "little-builders-tool-set-puzzle", name: "Little Builders Tool Set", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "A toolbox where every tool is a puzzle piece.\n\nHammer, saw, spanner and screwdriver, each cut to lift out of its own slot. Pretend play and shape matching in the same board.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/little-builders-tool-set-puzzle-0.jpg", "/images/lasercut/little-builders-tool-set-puzzle-1.jpg", "/images/lasercut/little-builders-tool-set-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 86mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "LI" },
    imageUrl: "/images/lasercut/little-builders-tool-set-puzzle-0.jpg" },
  { slug: "montessori-3d-layer-puzzle", name: "Montessori Layered Puzzle", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "Every layer is a step further in.\n\nA stacked Montessori puzzle where each level sits inside the one below. Depth, order and sequence in one object.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/montessori-3d-layer-puzzle-0.png", "/images/lasercut/montessori-3d-layer-puzzle-1.png", "/images/lasercut/montessori-3d-layer-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 130mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "MO" },
    imageUrl: "/images/lasercut/montessori-3d-layer-puzzle-0.png" },
  { slug: "number-maths-peg-board", name: "Number Maths Peg Board", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Numbers with handles.\n\nA pegged number board built for the age where everything gets picked up, turned over, and put somewhere else.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/number-maths-peg-board-0.jpg", "/images/lasercut/number-maths-peg-board-1.jpg", "/images/lasercut/number-maths-peg-board-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "195mm x 195mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "NU" },
    imageUrl: "/images/lasercut/number-maths-peg-board-0.jpg" },
  { slug: "owl-number-tower-puzzle", name: "Owl Number Tower", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "An owl that stacks itself, one number at a time.\n\nEach layer is a numbered piece, so the tower only stands when the counting is right. Stands up on the shelf when they are done.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/owl-number-tower-puzzle-0.png", "/images/lasercut/owl-number-tower-puzzle-1.png", "/images/lasercut/owl-number-tower-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "161mm x 195mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "OW" },
    imageUrl: "/images/lasercut/owl-number-tower-puzzle-0.png" },
  { slug: "rocket-number-puzzle", name: "Rocket Number Puzzle", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Count down from ten, then launch.\n\nA rocket built from numbered pieces, so the countdown is the puzzle. Preschool maths with somewhere to go.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/rocket-number-puzzle-0.png", "/images/lasercut/rocket-number-puzzle-1.jpg", "/images/lasercut/rocket-number-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "197mm x 99mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "RO" },
    imageUrl: "/images/lasercut/rocket-number-puzzle-0.png" },
  { slug: "sea-creatures-peg-board", name: "Sea Creatures Peg Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Fish, crab, octopus, turtle. All out by the peg.\n\nA rock-pool board with wooden pegs on every creature. Naming, matching and gripping, all in one.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/sea-creatures-peg-board-0.jpg", "/images/lasercut/sea-creatures-peg-board-1.jpg", "/images/lasercut/sea-creatures-peg-board-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "128mm x 117mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "SE" },
    imageUrl: "/images/lasercut/sea-creatures-peg-board-0.jpg" },
  { slug: "shape-peg-board", name: "Shape Peg Board", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "The very first shapes, on very easy pegs.\n\nBasic shapes with chunky wooden pegs. Where a toddler learns that things have a right way round.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/shape-peg-board-0.png", "/images/lasercut/shape-peg-board-1.png", "/images/lasercut/shape-peg-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "45mm x 135mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "SH" },
    imageUrl: "/images/lasercut/shape-peg-board-0.png" },
  { slug: "shape-stencil-set", name: "Shape Stencil Set", variant: "Good Value", price: 15, category: "Shapes & Montessori", stock: 999,
    description: "Trace it, draw it, learn it.\n\nCut-out shape stencils for tracing onto paper. The bridge between recognising a shape and being able to draw one.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/shape-stencil-set-0.jpg", "/images/lasercut/shape-stencil-set-1.jpg", "/images/lasercut/shape-stencil-set-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "169mm x 234mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "SH" },
    imageUrl: "/images/lasercut/shape-stencil-set-0.jpg" },
  { slug: "solar-system-peg-puzzle", name: "Solar System Peg Puzzle", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Eight planets, in the right order, every time.\n\nEach planet lifts out on its own peg and only fits its own orbit. The solar system small enough to hold.",
    details: { age: "4+", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/solar-system-peg-puzzle-0.png", "/images/lasercut/solar-system-peg-puzzle-1.jpg", "/images/lasercut/solar-system-peg-puzzle-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "175mm x 134mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "SO" },
    imageUrl: "/images/lasercut/solar-system-peg-puzzle-0.png" },
  { slug: "stacking-animal-friends-3d", name: "Stacking Animal Friends", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "Flat pieces that stand up into animals.\n\nSlot the pieces together and the puzzle becomes a creature that stands on its own. The moment it stops being flat is the moment they get hooked.",
    details: { age: "3-6", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/stacking-animal-friends-3d-0.png", "/images/lasercut/stacking-animal-friends-3d-1.png", "/images/lasercut/stacking-animal-friends-3d-2.png"], material: "3mm MDF, sanded by hand", dimensions: "143mm x 99mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "ST" },
    imageUrl: "/images/lasercut/stacking-animal-friends-3d-0.png" },
  { slug: "teddy-bear-layer-board", name: "Teddy Bear Layer Board", variant: "Good Value", price: 15, category: "Animals & Nature", stock: 999,
    description: "A bear that builds up in layers.\n\nStacked pieces that turn a flat board into a bear with depth. Soft shapes, rounded edges, made for small hands.",
    details: { age: "2-5", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/teddy-bear-layer-board-0.png", "/images/lasercut/teddy-bear-layer-board-1.png", "/images/lasercut/teddy-bear-layer-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "128mm x 128mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TE" },
    imageUrl: "/images/lasercut/teddy-bear-layer-board-0.png" },
  { slug: "toddler-alphabet-board", name: "Toddler Alphabet Board", variant: "Good Value", price: 15, category: "Alphabet & Literacy", stock: 999,
    description: "Bigger letters, for smaller hands.\n\nA chunkier alphabet board sized for toddlers who are not ready for small pieces yet. Same letters, easier grip.",
    details: { age: "2-4", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/toddler-alphabet-board-0.png", "/images/lasercut/toddler-alphabet-board-1.png", "/images/lasercut/toddler-alphabet-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "196mm x 131mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TO" },
    imageUrl: "/images/lasercut/toddler-alphabet-board-0.png" },
  { slug: "tractor-shape-puzzle", name: "Tractor Shape Puzzle", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "The tractor that teaches shapes on the way past.\n\nWheels, cab and trailer each lift out as their own shape. Ready to paint if you want it in your own colours.",
    details: { age: "2-4", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/tractor-shape-puzzle-0.png", "/images/lasercut/tractor-shape-puzzle-1.png", "/images/lasercut/tractor-shape-puzzle-2.png"], material: "3mm MDF, sanded by hand", dimensions: "201mm x 139mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/tractor-shape-puzzle-0.png" },
  { slug: "truck-peg-puzzle-1", name: "Truck Peg Puzzle, Design One", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "A truck built from shapes.\n\nEach part of the truck is a shape, and each shape lifts out on a peg. Two lessons in one small board.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-1-0.png", "/images/lasercut/truck-peg-puzzle-1-1.png", "/images/lasercut/truck-peg-puzzle-1-2.png"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 130mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-1-0.png" },
  { slug: "truck-peg-puzzle-2", name: "Truck Peg Puzzle, Design Two", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Another truck, another set of shapes.\n\nA second design in the truck peg series, with its own shape layout. Collect the set or pick a favourite.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-2-0.png", "/images/lasercut/truck-peg-puzzle-2-1.png", "/images/lasercut/truck-peg-puzzle-2-2.png"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 123mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-2-0.png" },
  { slug: "truck-peg-puzzle-3", name: "Truck Peg Puzzle, Design Three", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Shapes that drive.\n\nChunky pegged pieces that build a working-looking truck. Sized for the youngest puzzle age.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-3-0.png", "/images/lasercut/truck-peg-puzzle-3-1.png", "/images/lasercut/truck-peg-puzzle-3-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 135mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-3-0.png" },
  { slug: "truck-peg-puzzle-4", name: "Truck Peg Puzzle, Design Four", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Lift it, name it, put it back.\n\nA peg truck board with a different silhouette again. The repetition is the point at this age.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-4-0.png", "/images/lasercut/truck-peg-puzzle-4-1.png", "/images/lasercut/truck-peg-puzzle-4-2.png"], material: "3mm MDF, sanded by hand", dimensions: "198mm x 198mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-4-0.png" },
  { slug: "truck-peg-puzzle-5", name: "Truck Peg Puzzle, Design Five", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Big pegs, small hands, one truck.\n\nAnother in the toddler truck series. Simple shapes, generous pieces, nothing to lose under the sofa.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-5-0.png", "/images/lasercut/truck-peg-puzzle-5-1.png", "/images/lasercut/truck-peg-puzzle-5-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 75mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-5-0.png" },
  { slug: "truck-peg-puzzle-6", name: "Truck Peg Puzzle, Design Six", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "The last truck in the set.\n\nSixth design in the peg truck range. Same easy pegs, same satisfying fit, a different shape to learn.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/truck-peg-puzzle-6-0.jpg", "/images/lasercut/truck-peg-puzzle-6-1.jpg", "/images/lasercut/truck-peg-puzzle-6-2.jpg"], material: "3mm MDF, sanded by hand", dimensions: "129mm x 89mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "TR" },
    imageUrl: "/images/lasercut/truck-peg-puzzle-6-0.jpg" },
  { slug: "vehicles-peg-board", name: "Vehicles Peg Board", variant: "Good Value", price: 15, category: "Vehicles & Making", stock: 999,
    description: "Car, bus, boat, plane. Lift and learn.\n\nChunky pegged vehicles for the youngest hands. Naming things is half the play, fitting them is the other half.",
    details: { age: "1-3", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/vehicles-peg-board-0.png", "/images/lasercut/vehicles-peg-board-1.png", "/images/lasercut/vehicles-peg-board-2.png"], material: "3mm MDF, sanded by hand", dimensions: "130mm x 73mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "VE" },
    imageUrl: "/images/lasercut/vehicles-peg-board-0.png" },
  { slug: "watermelon-maths-game", name: "Watermelon Maths Game", variant: "Good Value", price: 15, category: "Numbers & Counting", stock: 999,
    description: "Slice the watermelon, solve the sum.\n\nA fruit that comes apart into maths. Halves, quarters and simple sums, in a shape that makes fractions obvious.",
    details: { age: "4+", made: "Made to order in 2 to 3 working days", images: ["/images/lasercut/watermelon-maths-game-0.png", "/images/lasercut/watermelon-maths-game-1.png", "/images/lasercut/watermelon-maths-game-2.png"], material: "3mm MDF, sanded by hand", dimensions: "195mm x 195mm", personalisation: "Add a name free of charge, just ask at checkout" },
    imagePlaceholder: { bg: "#C9A96E", initials: "WA" },
    imageUrl: "/images/lasercut/watermelon-maths-game-0.png" },
]

export function getProductBySlug(slug: string): Product | undefined { return products.find((p) => p.slug === slug && !p.hidden); }
export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return products.filter((p) => !p.hidden);
  return products.filter((p) => p.category === category && !p.hidden);
}
export function formatPrice(price: number): string { return "AED " + price.toString(); }
export function calculateSubtotal(items: { product: Product; quantity: number }[]): number {
  return items.reduce((sum, item) => sum + item.product.price * item.quantity, 0);
}

// The hidden flag stays in the type because the storefront filters on it.
// Hidden categories simply aren't emitted (no visible products in Postgres),
// so the flag is always undefined here — the filters still compile and pass.
export interface Category { name: string; description: string; icon: string; hidden?: boolean; }

export const categories: Category[] = [
  { name: "Vehicles & Making", description: "11 products", icon: "📦" },
  { name: "Numbers & Counting", description: "9 products", icon: "📦" },
  { name: "Alphabet & Literacy", description: "8 products", icon: "📦" },
  { name: "Animals & Nature", description: "7 products", icon: "📦" },
  { name: "Shapes & Montessori", description: "5 products", icon: "📦" },
  { name: "3D & Architecture", description: "1 products", icon: "📦" },
]
