# Generated by ops/selfhost/scripts/gen-app-container.py � safe to edit.
#
# Alpine (musl) rather than Next's official node:*-slim: on glibc, sharp needs
# memory-allocator tuning to avoid excessive usage, which this host cannot
# afford while running 15 database stacks.

# SINGLE builder stage � deliberately NOT the conventional deps/builder split.
#
# The usual pattern installs in a `deps` stage then does
#     COPY --from=deps /app/node_modules ./node_modules
# On this host that COPY measured **1433 seconds** (24 minutes) for one app:
# node_modules is hundreds of thousands of tiny files and Docker Desktop's
# Windows-backed filesystem copies them pathologically slowly. It dominated the
# entire build and made every attempt look like a hang.
#
# Installing in place keeps the same layer caching � the install layer still
# invalidates only when package.json / the lockfile change, because those are
# copied before the source � while removing the cross-stage copy completely.
FROM node:22-alpine AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json .npmrc* ./
ENV HUSKY=0
RUN npm ci --ignore-scripts \
 || ( echo '>> lockfile drift - regenerating in-image' \
      && npm install --package-lock-only --ignore-scripts --prefer-online \
      && npm ci --ignore-scripts )
COPY . .

# NEXT_PUBLIC_* are inlined into the client bundle AT BUILD TIME. Rather than a
# Docker ARG per variable per app, the caller passes them as one blob which Next
# loads natively from .env.production.local. Only NEXT_PUBLIC_* is passed �
# those values ship in the browser bundle anyway, so nothing secret is baked in.
ARG BUILD_ENV=""
RUN printf '%s\n' "$BUILD_ENV" > .env.production.local

# Read by next.config -> deploymentId. Must be an ARG: Next embeds it during
# `next build`, so supplying it only at runtime leaves version-skew protection
# silently off.
#
# Defaulted rather than required, because Coolify's git build pack passes no
# such arg. An unset DEPLOYMENT_ID emits assets with no `?dpl=`, and that query
# parameter is exactly what `npm run verify:deploy` reads to tell a live build
# from a stale one -- so the check that catches an undeployed commit would be
# the first casualty of deploying from git. The fallback is a UTC build stamp:
# verify-deploy.mjs matches /dpl=(\d+)/ and orders ids numerically, so whatever
# is substituted here has to stay digits.
ARG DEPLOYMENT_ID=""
ENV NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=production

# Source-map upload needs a token and fails offline; errors still report at runtime.
ENV SENTRY_SKIP_AUTO_RELEASE=1
RUN DEPLOYMENT_ID="${DEPLOYMENT_ID:-$(date -u +%Y%m%d%H%M%S)}" \
 && export DEPLOYMENT_ID \
 && echo ">> building with DEPLOYMENT_ID=$DEPLOYMENT_ID" \
 && npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Belt-and-braces: Next's tracer sometimes omits @swc/helpers.
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/@swc/helpers ./node_modules/@swc/helpers

# ISR writes here. A volume is mounted over it by apps/app.yml so the cache
# survives restarts; without that, every restart discards every regenerated page.
RUN mkdir -p .next/cache && chown -R nextjs:nodejs .next

USER nextjs
EXPOSE 3000
ENV PORT=3000 HOSTNAME=0.0.0.0
CMD ["node", "server.js"]
