// Generated by ops/qa/rollout.py — MASTER-QA-PROTOCOL §6 public-route smoke.
// Regenerate the sitemap: node ../../../../ops/qa/discover-routes.mjs .
//
// The kit is imported from the VENDORED copy at <repo>/ops/qa, three levels up,
// not four. Four escaped the repository entirely and resolved only on the
// operator's workstation — `npm run typecheck:e2e` in CI caught it with
// TS2307 the first time that step existed.
import { test, expect } from "@playwright/test";
import { registerSmokeSuite } from "../../../ops/qa/smoke-suite";
import sitemap from "../../fixtures/sitemap.json";

registerSmokeSuite({ test, expect }, sitemap.routes, {
  // API routes are not pages; they get their own module in a later stage.
  skip: [/^\/api\//],
});
