// Generated by ops/qa/rollout.py — MASTER-QA-PROTOCOL §6 public-route smoke.
// Regenerate the sitemap: node ../../../../ops/qa/discover-routes.mjs .
import { test, expect } from "@playwright/test";
import { registerSmokeSuite } from "../../../../ops/qa/smoke-suite";
import sitemap from "../../fixtures/sitemap.json";

registerSmokeSuite({ test, expect }, sitemap.routes, {
  // API routes are not pages; they get their own module in a later stage.
  skip: [/^\/api\//],
});
