/**
 * The one sustained warm note under each end card.
 *
 * Synthesised with ffmpeg rather than generated by a model. A single held note
 * is a fundamental plus a few decaying harmonics — that is a specification, not
 * a creative brief, and building it directly makes it free, deterministic, and
 * exactly as long as the shot it sits under.
 *
 * WARMTH COMES FROM THREE THINGS, none of which a bare sine has:
 *   - harmonics at 2f/3f/4f, each much quieter than the last, which is roughly
 *     what a struck or bowed instrument does
 *   - a second voice detuned by a fraction of a hertz, so the two drift in and
 *     out of phase and the note breathes instead of sitting dead still
 *   - a lowpass, because the upper harmonics of a synthesised tone are what
 *     make it sound like a test signal
 *
 * One file per film, cut to that film's closing shot. A single shared file
 * would have its release truncated by whichever film's close is shorter, and a
 * fade-out that gets cut off is just an abrupt stop.
 *
 * Usage: node note.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const run = promisify(execFile);
const HERE = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"));
const OUT = path.join(HERE, "public", "audio", "bed");
fs.mkdirSync(OUT, { recursive: true });

/** C3. Low enough to sit under a voice, high enough to survive a phone speaker. */
const F = 130.81;

/**
 * [name, seconds, loudness target] — one per film's closing shot.
 *
 * THE TWO TARGETS DIFFER, and that is not an oversight. Both notes started at
 * -30 LUFS: under the foley, above the room tone, present without competing
 * with the wordmark. In "The Making" that is exactly right — the note stands
 * 11 dB clear, because its closing shot carries one short line and is otherwise
 * quiet.
 *
 * In "The Correction" it was inaudible. That film's close is narrated almost
 * end to end — "Nothing is made until you ask for it" then "Lebon Grace" cover
 * 5.5 of its 6 seconds — and a -30 LUFS pad under a -16 LUFS voice is simply
 * masked. An A/B render of the closing shot with and without it differed by
 * 0.5 dB: technically present, audibly absent.
 *
 * So the narrated close gets a louder note. -23 still sits 7 dB under the
 * voice, which is an ordinary bed level beneath narration.
 */
const NOTES = [
  ["note-making", 165 / 30, -30],      // 5.5s, mostly unnarrated close
  ["note-correction", 180 / 30, -23],  // 6.0s, narrated end to end
];

for (const [name, secs, TARGET] of NOTES) {
  const dest = path.join(OUT, `${name}.mp3`);
  const d = secs.toFixed(3);

  // Six sines: fundamental and three harmonics, plus a detuned pair that beats
  // slowly against the fundamental.
  const inputs = [
    [F, 1.0], [F * 2, 0.34], [F * 3, 0.16], [F * 4, 0.07],
    [F + 0.4, 0.55], [F * 2 + 0.3, 0.18],
  ];

  const args = ["-hide_banner", "-loglevel", "error", "-y"];
  for (const [freq] of inputs) {
    args.push("-f", "lavfi", "-i", `sine=frequency=${freq.toFixed(3)}:duration=${d}`);
  }

  // Attack is slow — the note should arrive under the wordmark rather than
  // announce itself. Release runs to the very last frame.
  const attack = 1.4;
  const release = Math.min(2.2, secs * 0.45);
  const filter =
    inputs.map((_, i) => `[${i}:a]`).join("") +
    `amix=inputs=${inputs.length}:weights=${inputs.map(([, w]) => w).join(" ")}:normalize=0[m];` +
    `[m]lowpass=f=1800,` +
    `afade=t=in:st=0:d=${attack}:curve=qsin,` +
    `afade=t=out:st=${(secs - release).toFixed(3)}:d=${release.toFixed(3)}:curve=qsin,` +
    `loudnorm=I=${TARGET}:TP=-2:LRA=11[a]`;

  args.push("-filter_complex", filter, "-map", "[a]",
            "-c:a", "libmp3lame", "-q:a", "2", dest);
  await run("ffmpeg", args);

  const { stderr } = await run("ffmpeg", [
    "-hide_banner", "-i", dest, "-af", "loudnorm=print_format=json", "-f", "null", "-",
  ]);
  const j = JSON.parse(stderr.slice(stderr.lastIndexOf("{"), stderr.lastIndexOf("}") + 1));
  const { stdout } = await run("ffprobe", [
    "-v", "error", "-show_entries", "format=duration", "-of", "default=nw=1:nk=1", dest,
  ]);
  console.log(
    `${name.padEnd(18)} ${parseFloat(stdout).toFixed(2)}s (want ${secs.toFixed(2)})  ` +
    `${Number(j.input_i).toFixed(1)} LUFS (target ${TARGET})`,
  );
}
