/**
 * Prepare the chosen stock clips for the "Making" film.
 *
 * Each clip is trimmed to a centred segment of exactly the length the edit
 * needs, scaled to 1920x1080 (cover-cropped, never letterboxed), stripped of
 * audio and re-encoded at 30fps so Remotion gets a uniform, seekable source.
 *
 * WHY CENTRED: the useful action is almost always mid-clip — stock clips open
 * and close on the camera settling. Taking the middle avoids hand-picking in
 * and out points for every clip.
 *
 * The clips chosen here were each verified by looking at extracted frames, not
 * by trusting the search title. Four clips titled "laser cutting wood" turned
 * out to be industrial metal lasers throwing sparks, and three doorstep clips
 * carried visible Amazon branding, which both stock licences bar from
 * commercial use.
 */
import fs from "node:fs";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const run = promisify(execFile);
const HERE = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"));
const SRC = "C:/Users/user/AppData/Local/Temp/claude/C--Users-user-Desktop-aprojects-lebon-grace--claude-worktrees-lebon-grace-review-12cdd4/b843391a-0739-4b76-a980-8fcfae50c9f7/scratchpad/stock/picks";

/** Generated shots live in the repo, not the scratchpad — they cost money. */
const LTX = path.join(HERE, "..", ".ltx-takes");
/** Veo clips, generated by hand in the Gemini app and dropped in Downloads. */
const VEO = "C:/Users/user/Downloads";
const OUT = path.join(HERE, "public", "stock");
fs.mkdirSync(OUT, { recursive: true });

/**
 * pick key -> [output name, seconds needed by the edit].
 *
 * Each length is the MAXIMUM the clip is asked for across BOTH films, not the
 * length either one uses alone. Two films share these files, and a Sequence
 * longer than its source does not error — it simply holds the last frame, which
 * reads as a freeze nobody would notice until it shipped. Prepping to the
 * longest demand makes that impossible.
 *
 *   order 4s (making) / 5s (correction)   -> 5
 *   sheet 3.5s / 5s                       -> 5
 *   cut   4.5s / 3s                       -> 4.5
 *   lift  3.5s / 5s                       -> 5
 *   sand  4.5s / 3s                       -> 4.5
 *   pack  4s   / 3s                       -> 4
 *   play  4.5s / 4s                       -> 4.5
 *   colour 4.5s / 4s                      -> 4.5
 */
const CLIPS = [
  // 8s for the three that carry a spoken correction. The Correction's statement
  // shots grew from 150 to 240 frames once the voice was added: the device gives
  // a line 1.87s and the unhurried read needs 2.9s, so at the old length the
  // replacement line started while the struck line was still being spoken.
  ["1-order_2",   "order",  8],
  ["3-cut_7",     "sheet",  8],
  // The fourth statement shot needed a source longer than 8s and `lift` is only
  // 7.0s, so it gets its own clip rather than being stretched or held.
  ["3-cut_5",     "inspect", 8],
  // ── generated on Veo, and the best footage this project has had ─────────
  // These replace the fal LTX-2.3 takes. The material finally reads correctly:
  // uniform grainless MDF rather than planked pine, because the prompts stopped
  // saying "wooden" — the word was overriding three explicit instructions not
  // to render wood grain.
  //
  // EXPLICIT START TIMES, not centred trims. Each of these is a continuous
  // shot with a beginning and an end, so a centred window would cut across the
  // beat. `cut` and `lift` come from the SAME 10s clip: the laser traces its
  // curve for the first five seconds, then hands come in and lift the piece
  // out. One generation, two shots.
  ["A_single_continuous_extreme_ma",     "cut",  4.5, VEO, 0.6],
  // NOT the Veo lift. That clip's second half fails a frame check: the piece in
  // the hands changes silhouette between 2.2s and 3.0s, and neither shape
  // matches the hole it supposedly came from. Real footage of hands sorting cut
  // pieces is honest and has no geometry to get wrong.
  ["5-lift_1",                           "lift", 3.5],
  // Opens on a blank board and burns LUCY in, correctly spelled. Starts at 3.4s
  // so the shot begins as the first letter appears rather than on empty board.
  ["A_single_continuous_extreme_ma (1)", "name", 5.5, VEO, 3.4],
  // NOT the Veo child clip, despite it showing an alphabet board. The letters
  // on that board are MIRRORED AND GARBLED — after A B C D it degenerates into
  // nonsense. On a product whose whole purpose is teaching the alphabet that is
  // disqualifying; a parent sees it immediately. Back to real stock footage of
  // a child's hands on a wooden puzzle board.
  ["P-puzzle_6",                         "play", 4.5],
  ["6-sand_3",    "sand",   4.5],
  ["8-packed_0",  "pack",   4],
  // A child colouring in a printed outline. Hands only — no identifiable face.
  // Neither stock licence guarantees a model release, and an advert built
  // around an identifiable child is the worst place to discover that.
  //
  // The stock `play` clip that used to sit here (P-puzzle_6) is gone: the Veo
  // shot above shows a child with an alphabet board, which is the actual
  // product rather than generic wooden toys. It was still listed after the Veo
  // entry and silently overwrote it — same output name, later line wins.
  ["C-colour_45", "colour", 4.5],
];

for (const [key, name, secs, dir, at] of CLIPS) {
  const src = path.join(dir ?? SRC, `${key}.mp4`);
  const dst = path.join(OUT, `${name}.mp4`);

  const { stdout } = await run("ffprobe", [
    "-v", "error", "-show_entries", "format=duration",
    "-of", "default=nw=1:nk=1", src,
  ]);
  const dur = parseFloat(stdout.trim());
  if (dur < secs) throw new Error(`${key}: ${dur.toFixed(1)}s source cannot fill a ${secs}s slot`);

  // Centred by default; `at` overrides it for clips whose action has a shape
  // that a centred window would cut across.
  const start = at !== undefined ? at : Math.max(0, (dur - secs) / 2);
  if (start + secs > dur + 0.05) {
    throw new Error(`${key}: ${secs}s from ${start}s exceeds the ${dur.toFixed(1)}s source`);
  }

  await run("ffmpeg", [
    "-hide_banner", "-loglevel", "error", "-y",
    "-ss", start.toFixed(2), "-t", String(secs), "-i", src,
    "-vf", "scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,fps=30",
    "-an", "-c:v", "libx264", "-preset", "slow", "-crf", "18",
    "-pix_fmt", "yuv420p", "-movflags", "+faststart",
    dst,
  ]);

  // Confirm the output is really the geometry and length the edit assumes,
  // rather than trusting that ffmpeg did what was asked.
  const probe = await run("ffprobe", [
    "-v", "error", "-select_streams", "v:0",
    "-show_entries", "stream=width,height,nb_frames:format=duration",
    "-of", "default=nw=1:nk=1", dst,
  ]);
  const [w, h, frames, outDur] = probe.stdout.trim().split(/\r?\n/);
  const ok = Number(w) === 1920 && Number(h) === 1080 && Math.abs(Number(outDur) - secs) < 0.2;
  console.log(
    `${name.padEnd(6)} <- ${key.padEnd(12)} src ${dur.toFixed(1)}s @${start.toFixed(1)}  ` +
    `out ${w}x${h} ${Number(outDur).toFixed(2)}s ${frames}f ${ok ? "OK" : "<-- WRONG"}`,
  );
}
