#!/usr/bin/env node
/**
 * Generate the STAGING stack's secrets and render its kong config (TR-03).
 *
 *   node ops/staging/gen-secrets.mjs
 *
 * Called by setup.sh, which runs it inside a throwaway `node:22-alpine`
 * container — cx53 has no node, and installing a runtime on shared
 * infrastructure to run one setup script is a poor trade.
 *
 * Split from the orchestration deliberately: this half is pure (no docker, no
 * network, no database), so it can be run and reasoned about anywhere. The half
 * that touches containers is bash, where that work belongs.
 *
 * SECRETS. Every credential here is generated locally with `crypto.randomBytes`
 * and written to `.env.staging` with mode 0600. Nothing is echoed to stdout —
 * not truncated, not partially masked. A secret printed to a terminal is a
 * secret in a scrollback buffer, a log, and a transcript. `--status` reports
 * lengths and never values.
 *
 * These credentials protect a database whose entire purpose is to be destroyed
 * by tests. They are still generated properly, because "it's only staging" is
 * how a reused password ends up somewhere that matters.
 */
import { createHmac, randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ENV_FILE = join(HERE, ".env.staging");
const KONG_OUT = join(HERE, "kong.yml");

/** base64url without padding — what JWT requires. */
const b64u = (buf) => Buffer.from(buf).toString("base64url");

/**
 * A Supabase-shaped JWT.
 *
 * Supabase keys are ordinary HS256 JWTs carrying a `role` claim; PostgREST
 * reads that claim and assumes the matching Postgres role. `service_role`
 * bypasses RLS, which is what the app's server-side code needs and what must
 * never reach a browser.
 */
function makeJwt(role, secret, years = 10) {
  const iat = Math.floor(Date.parse("2026-01-01T00:00:00Z") / 1000);
  const header = b64u(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const payload = b64u(
    JSON.stringify({ role, iss: "supabase", iat, exp: iat + years * 365 * 24 * 3600 })
  );
  const sig = createHmac("sha256", secret).update(`${header}.${payload}`).digest("base64url");
  return `${header}.${payload}.${sig}`;
}

function loadEnv() {
  if (!existsSync(ENV_FILE)) return null;
  const out = {};
  for (const line of readFileSync(ENV_FILE, "utf8").split("\n")) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function generateEnv() {
  if (existsSync(ENV_FILE)) {
    console.log("  .env.staging already exists — keeping the existing secrets");
    return loadEnv();
  }
  // 40 chars: Supabase's own minimum for JWT_SECRET.
  const JWT_SECRET = randomBytes(32).toString("hex");
  const POSTGRES_PASSWORD = randomBytes(24).toString("base64url");
  const env = {
    POSTGRES_PASSWORD,
    JWT_SECRET,
    ANON_KEY: makeJwt("anon", JWT_SECRET),
    SERVICE_ROLE_KEY: makeJwt("service_role", JWT_SECRET),
  };
  writeFileSync(
    ENV_FILE,
    "# GENERATED by ops/staging/setup.mjs — do not commit (see .gitignore).\n" +
      "# Staging only. Nothing here is used by the live shop.\n" +
      Object.entries(env).map(([k, v]) => `${k}=${v}`).join("\n") + "\n",
    { mode: 0o600 }
  );
  chmodSync(ENV_FILE, 0o600);
  console.log("  .env.staging written (0600), 4 secrets generated");
  return env;
}

function renderKong(env) {
  const tpl = readFileSync(join(HERE, "kong.template.yml"), "utf8");
  const out = tpl
    .replace(/\$\{ANON_KEY\}/g, env.ANON_KEY)
    .replace(/\$\{SERVICE_ROLE_KEY\}/g, env.SERVICE_ROLE_KEY);
  if (out.includes("${")) throw new Error("kong.template.yml has an unsubstituted placeholder");
  writeFileSync(KONG_OUT, out, { mode: 0o600 });
  console.log("  kong.yml rendered from template");
}

// ── main ─────────────────────────────────────────────────────────────────────

const env = generateEnv();
renderKong(env);
console.log("  secrets and kong.yml ready");
