#!/usr/bin/env node
/**
 * Generate the MASTER-QA-PROTOCOL §5.1 artifacts from the codebase.
 *
 *   npm run qa:report            # regenerate the three derivable documents
 *
 * ── Why these are GENERATED ──────────────────────────────────────────────────
 *
 * The protocol asks for a SYSTEM_MAP, a COVERAGE_INVENTORY and a
 * ROUTE_COVERAGE_REPORT. Hand-written, all three are stale within a fortnight —
 * this repository already proved it: `tests/fixtures/sitemap.json` was a
 * hand-triggered snapshot and had silently drifted two routes behind the app.
 * A document nobody trusts is worse than no document, because it is consulted
 * once and believed.
 *
 * So anything derivable is derived: routes from the filesystem, endpoints from
 * their route handlers, tables from the migrations, coverage from the actual
 * test files, and the route report from a real Playwright run.
 *
 * What is NOT generated, and is hand-written on purpose:
 *   docs/QA/BUGS.md            what broke and how it was proven — judgement
 *   docs/QA/LESSONS_LEARNED.md prevention patterns — judgement
 *   docs/QA/TODO.md            points at ACTION_PLAN.md rather than copying it
 *
 * Duplicating ACTION_PLAN.md or CODEBASE_AUDIT.md into docs/QA/ would create a
 * second source of truth that disagrees with the first. Where content already
 * exists, these link to it.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const OUT = join(ROOT, "docs", "QA");
mkdirSync(OUT, { recursive: true });

const GENERATED = (source) =>
  `<!-- GENERATED by scripts/qa-report.mjs — do not edit by hand.\n` +
  `     Regenerate with \`npm run qa:report\`. Source: ${source} -->\n\n`;

// ── discovery ────────────────────────────────────────────────────────────────

function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

/** Page routes, from the App Router's filesystem convention. */
function pageRoutes() {
  const pages = walk(join(ROOT, "src", "app")).filter((p) => p.endsWith("page.tsx"));
  return pages
    .map((p) => {
      const rel = relative(join(ROOT, "src", "app"), p).replace(/\\/g, "/").replace(/\/page\.tsx$/, "");
      return rel === "page.tsx" ? "/" : `/${rel}`;
    })
    .sort();
}

/** API endpoints and the verbs each actually exports. */
function apiRoutes() {
  return walk(join(ROOT, "src", "app", "api"))
    .filter((p) => p.endsWith("route.ts"))
    .map((p) => {
      const src = readFileSync(p, "utf8");
      const verbs = [...src.matchAll(/export async function (GET|POST|PUT|DELETE|PATCH)/g)].map((m) => m[1]);
      const path = "/" + relative(join(ROOT, "src", "app"), p).replace(/\\/g, "/").replace(/\/route\.ts$/, "");
      return { path, verbs, adminOnly: /requireAdmin/.test(src), rateLimited: /rateLimit\(/.test(src) };
    })
    .sort((a, b) => a.path.localeCompare(b.path));
}

/** Tables, from the forward migrations rather than a remembered schema. */
function tables() {
  const dir = join(ROOT, "supabase", "migrations");
  const sql = walk(dir).filter((p) => p.endsWith(".sql")).map((p) => readFileSync(p, "utf8")).join("\n");
  return [...new Set([...sql.matchAll(/CREATE TABLE (?:IF NOT EXISTS )?public\.([a-z_]+)/g)].map((m) => m[1]))].sort();
}

/** Test files with their case counts, so coverage is counted not claimed. */
function testFiles() {
  const specs = [...walk(join(ROOT, "tests")), ...walk(join(ROOT, "src"))].filter((p) =>
    /\.(spec|test)\.tsx?$/.test(p)
  );
  return specs
    .map((p) => {
      const src = readFileSync(p, "utf8");
      const cases = (src.match(/^\s*(?:it|test)(?:\.each\([^)]*\))?\(/gm) || []).length;
      const file = relative(ROOT, p).replace(/\\/g, "/");
      return { file, cases, kind: file.startsWith("tests/e2e/") ? "e2e" : "unit" };
    })
    .sort((a, b) => a.file.localeCompare(b.file));
}

// ── documents ────────────────────────────────────────────────────────────────

function systemMap() {
  const pages = pageRoutes();
  const api = apiRoutes();
  const tbl = tables();

  return (
    GENERATED("src/app, supabase/migrations") +
    `# System map\n\n` +
    `MASTER-QA-PROTOCOL §5.1. What exists, so a tester knows what to cover.\n\n` +
    `## Roles\n\n` +
    `Two, and that is the whole list.\n\n` +
    `| Role | How it is established | Reaches |\n|---|---|---|\n` +
    `| Public | nothing — there are no customer accounts | everything except \`/admin\` |\n` +
    `| Admin | single password → httpOnly signed cookie (\`src/lib/admin-auth.ts\`) | \`/admin\`, and the admin verbs below |\n\n` +
    `There are **no subscription tiers, no plan entitlements and no customer login**. ` +
    `Guest checkout only; an order is looked up by **order id + phone**, which is therefore the ` +
    `entire authorisation model for customer data.\n\n` +
    `## Pages (${pages.length})\n\n` +
    pages.map((r) => `- \`${r}\``).join("\n") +
    `\n\n## API (${api.length})\n\n` +
    `| Endpoint | Verbs | Admin only | Rate limited |\n|---|---|---|---|\n` +
    api
      .map((a) => `| \`${a.path}\` | ${a.verbs.join(", ") || "—"} | ${a.adminOnly ? "yes" : "—"} | ${a.rateLimited ? "yes" : "—"} |`)
      .join("\n") +
    `\n\n## Tables (${tbl.length})\n\n` +
    tbl.map((t) => `- \`public.${t}\``).join("\n") +
    `\n\nSchema is \`supabase/migrations/\` — baseline plus forward migrations. ` +
    `\`bash scripts/verify-migrations.sh\` proves that set reproduces production.\n\n` +
    `## Integrations\n\n` +
    `| Service | Used for | Failure surface |\n|---|---|---|\n` +
    `| Stripe | checkout sessions, webhook | \`/api/checkout\`, \`/api/stripe-webhook\` |\n` +
    `| Supabase (self-hosted Postgres) | all persistence, via service role | every DB-backed route |\n` +
    `| Resend | order and status email | \`src/lib/email.ts\` |\n` +
    `| Umami | analytics, proxied first-party at \`/stats\` | \`src/components/Analytics.tsx\` |\n` +
    `| Sentry / GlitchTip | error reporting, and uptime alerts | \`SENTRY_DSN\` |\n` +
    `| WhatsApp | order notifications | \`src/lib/whatsapp.ts\` |\n`
  );
}

function coverageInventory(tests) {
  const unit = tests.filter((t) => t.kind === "unit");
  const e2e = tests.filter((t) => t.kind === "e2e");
  const total = tests.reduce((n, t) => n + t.cases, 0);

  return (
    GENERATED("test files under src/ and tests/") +
    `# Coverage inventory\n\n` +
    `MASTER-QA-PROTOCOL §5.1. Counted from the test files, not asserted.\n\n` +
    `**${total} cases** — ${unit.reduce((n, t) => n + t.cases, 0)} unit, ` +
    `${e2e.reduce((n, t) => n + t.cases, 0)} browser.\n\n` +
    `Browser tests run under **three viewports** (desktop 1920×1080, iPhone 14 Pro, ` +
    `Pixel 7), so the executed count is higher than the case count below.\n\n` +
    `## Browser (E2E)\n\n| File | Cases |\n|---|---:|\n` +
    e2e.map((t) => `| \`${t.file}\` | ${t.cases} |`).join("\n") +
    `\n\n> \`navigation/smoke.spec.ts\` registers its cases from ` +
    `\`tests/fixtures/sitemap.json\` at runtime, so it counts 0 here and executes one per route.\n\n` +
    `## Unit\n\n| File | Cases |\n|---|---:|\n` +
    unit.map((t) => `| \`${t.file}\` | ${t.cases} |`).join("\n") +
    `\n\n## Deliberately not covered\n\n` +
    `| Area | Why |\n|---|---|\n` +
    `| Stripe's hosted payment page | not ours to test |\n` +
    `| A real Stripe session | the account is live; \`/api/checkout\` is intercepted in the browser instead |\n` +
    `| Persona / plan matrices (§2.1, §2.2) | no accounts and no plans exist — see the system map |\n` +
    `| Registration, login, password reset (Module A) | no customer login exists |\n`
  );
}

/** Route coverage from a real Playwright run, if one has been recorded. */
function routeCoverage() {
  const results = join(ROOT, "playwright-results.json");
  if (!existsSync(results)) {
    return (
      GENERATED("playwright-results.json (absent)") +
      `# Route coverage report\n\n` +
      `No run recorded. Generate one:\n\n` +
      "```bash\nnpx playwright test --reporter=json > playwright-results.json && npm run qa:report\n```\n"
    );
  }

  const data = JSON.parse(readFileSync(results, "utf8"));
  const rows = [];
  const visit = (suite) => {
    for (const spec of suite.specs || []) {
      for (const t of spec.tests || []) {
        rows.push({
          title: spec.title,
          project: t.projectName,
          status: t.status === "expected" ? "pass" : t.status === "skipped" ? "skipped" : "FAIL",
        });
      }
    }
    for (const child of suite.suites || []) visit(child);
  };
  for (const s of data.suites || []) visit(s);

  const byStatus = rows.reduce((acc, r) => ((acc[r.status] = (acc[r.status] || 0) + 1), acc), {});
  const failures = rows.filter((r) => r.status === "FAIL");
  const routeRows = rows.filter((r) => /renders without defects/.test(r.title));

  return (
    GENERATED("playwright-results.json") +
    `# Route coverage report\n\n` +
    `MASTER-QA-PROTOCOL §6 Module B. From the last recorded Playwright run.\n\n` +
    `**${rows.length} executions** — ` +
    Object.entries(byStatus).map(([k, v]) => `${v} ${k}`).join(", ") +
    `.\n\n## Routes visited\n\n| Route | Project | Result |\n|---|---|---|\n` +
    routeRows
      .map((r) => `| \`${r.title.replace(/ renders without defects$/, "")}\` | ${r.project} | ${r.status} |`)
      .join("\n") +
    (failures.length
      ? `\n\n## Failures\n\n` + failures.map((f) => `- **${f.title}** (${f.project})`).join("\n") + "\n"
      : `\n\n## Failures\n\nNone.\n`) +
    `\n## Not reachable by crawl\n\n` +
    `| Route | Why |\n|---|---|\n` +
    `| \`/shop/[slug]\` | dynamic; covered explicitly by the money-path suite |\n` +
    `| \`/admin\` (past login) | needs the admin password; the login screen itself is crawled |\n` +
    `| \`/api/*\` | not pages — excluded in \`smoke.spec.ts\` and covered by unit tests |\n`
  );
}

// ── write ────────────────────────────────────────────────────────────────────

const tests = testFiles();
const written = [
  ["SYSTEM_MAP.md", systemMap()],
  ["COVERAGE_INVENTORY.md", coverageInventory(tests)],
  ["ROUTE_COVERAGE_REPORT.md", routeCoverage()],
];
for (const [name, body] of written) {
  writeFileSync(join(OUT, name), body, "utf8");
  console.log(`  docs/QA/${name}`);
}
console.log(`\n${tests.reduce((n, t) => n + t.cases, 0)} test cases across ${tests.length} files.`);
