-- 0012 — custom design requests, the conversation that happens before the order
--
-- Task #72. Photo and logo engraving cannot work like the name field does. A
-- name is a string the customer types and we cut verbatim. Artwork has to be
-- looked at, discussed, sometimes redrawn, and agreed before anyone fires a
-- laser at a AED 15 board.
--
-- So this is deliberately NOT an upload at checkout. Taking the money first
-- would mean either cutting something the customer never approved, or holding a
-- paid order hostage to a conversation. This table holds that conversation
-- instead: the customer submits artwork and a brief, the operator agrees the
-- design, and only then does a normal AED 15 order exist.
--
-- The price is unchanged. Photo and logo are further personalisation options on
-- the existing catalogue, not a separate product, so there is no quote, no
-- payment link and no second price anywhere in this schema.

CREATE TABLE IF NOT EXISTS public.design_requests (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The short human-quotable handle. The customer and the operator will say
  -- this to each other on WhatsApp, so it is separate from the uuid: nobody
  -- reads a uuid aloud. Generated by the application, not the database, because
  -- it needs to avoid ambiguous characters rather than be merely unique.
  reference    text NOT NULL UNIQUE,

  created_at   timestamptz NOT NULL DEFAULT now(),

  customer_name  text NOT NULL,
  customer_email text NOT NULL,
  -- Optional: the shop reaches most people on WhatsApp, but an email address is
  -- the one contact detail we can be sure a form gives us.
  customer_phone text,

  -- What they want made. Free text on purpose; this is the start of a
  -- conversation, not a spec.
  brief        text NOT NULL,

  -- WHERE THE FILE LIVES, not the file itself. The object key in R2, under a
  -- PRIVATE prefix. Postgres is not a blob store and a table the operator reads
  -- constantly should not carry megabytes of photograph.
  --
  -- Nullable because a request row is created before the upload is confirmed:
  -- if validation rejects the file, the row still records the attempt rather
  -- than vanishing, which is what makes abuse visible.
  artwork_key   text,
  -- The content type WE determined by inspecting the bytes, never the one the
  -- browser claimed. Stored so the operator's viewer can set it explicitly
  -- rather than sniffing again.
  artwork_type  text,
  artwork_bytes integer,

  -- submitted  the form arrived, artwork may or may not have landed
  -- discussing the operator is talking to the customer
  -- approved   the design is agreed and may be cut
  -- ordered    a real order exists, see order_id
  -- declined   we are not making this
  -- expired    abandoned, artwork deleted from R2
  --
  -- NOT NULL beside the CHECK, deliberately. A CHECK evaluates to unknown on
  -- NULL and therefore PASSES, which is the trap noted in migration 0002.
  status       text NOT NULL DEFAULT 'submitted'
    CHECK (status IN ('submitted','discussing','approved','ordered','declined','expired')),

  -- Set when the customer finally buys. Nullable for the whole life of the
  -- conversation, which is most of it.
  --
  -- ON DELETE SET NULL rather than CASCADE: if an order is ever removed, the
  -- design conversation and its artwork are still a real thing that happened,
  -- and deleting the customer's submitted photograph as a side effect of an
  -- order cleanup would be a surprise.
  order_id     uuid REFERENCES public.orders(id) ON DELETE SET NULL,

  -- Abandoned requests must not accumulate forever. Customers upload
  -- photographs of their children; holding those indefinitely because someone
  -- changed their mind is both a storage cost and a privacy liability. A sweep
  -- deletes the R2 object and sets status to 'expired' past this date.
  expires_at   timestamptz NOT NULL DEFAULT (now() + interval '90 days'),

  -- Free text for the operator. What was agreed, what was redrawn, why it was
  -- declined. The workshop reads this beside the artwork.
  operator_note text
);

-- The operator queue: everything still open, oldest first. This is the only
-- query shape the admin page needs.
CREATE INDEX IF NOT EXISTS design_requests_status_created_idx
  ON public.design_requests (status, created_at);

-- The expiry sweep, which asks only for rows past their date that still hold an
-- object. Partial, because the vast majority of rows will never match.
CREATE INDEX IF NOT EXISTS design_requests_expiry_idx
  ON public.design_requests (expires_at)
  WHERE artwork_key IS NOT NULL AND status <> 'expired';

-- Deny by default, like every other table here. The application reads and
-- writes through the service role, which bypasses RLS. The anon key is
-- published to browsers, so it gets no policy at all.
--
-- This one matters more than most: the table holds names, email addresses,
-- phone numbers and pointers to photographs of children.
ALTER TABLE public.design_requests ENABLE ROW LEVEL SECURITY;

-- Rollback:
--     DROP TABLE public.design_requests;
